import React, { useState, useMemo, useCallback, useRef, useEffect, startTransition, useDeferredValue } from "react";
import RolesCatalog from "./RolesCatalog.jsx";
import OperationsCatalog from "./OperationsCatalog.jsx";
import IaCPanel from "./IaCPanel.jsx";

// ─── ENGINE ─────────────────────────────────────────────────────────────────
const _reCache = new Map();
function mw(p, o) { if (p === o) return !0; if (p === "*") return !0; if (p === "*/read") return o.endsWith("/read"); let re = _reCache.get(p); if (!re) { re = new RegExp("^" + p.replace(/[.+?^${}()|[\]\\]/g, "\\$&").replace(/\\\./g, "\\.").replace(/\*/g, ".*") + "$", "i"); _reCache.set(p, re) } return re.test(o) }
function rc(r, op) { const pool = op.type === "dataAction" ? (r.dataActions || []) : (r.actions || []), not = op.type === "dataAction" ? (r.notDataActions || []) : (r.notActions || []); return pool.some(p => mw(p, op.action)) && !not.some(p => mw(p, op.action)) }
function findRoles(roles, ops) { if (!ops.length) return []; const total = ops.length, minC = Math.ceil(total * 0.6); return roles.map(r => { const ha = (r.actions || []).some(a => a.includes("*")), hd = (r.dataActions || []).some(a => a.includes("*")); if (!ha && !hd) { const maxP = (r.actions || []).length + (r.dataActions || []).length; if (maxP < minC) return null } let covered = 0; const missed = []; for (const o of ops) { if (rc(r, o)) covered++; else missed.push(o) } if (covered < minC) return null; return { ...r, coveredCount: covered, missedOps: missed, missedCount: missed.length, coverage: covered / total, est: r._estimatedActions || 1 } }).filter(Boolean).sort((a, b) => b.coverage !== a.coverage ? b.coverage - a.coverage : a.est - b.est).slice(0, 10) }
function mkJSON(ops, dataset) {
  if (dataset === "entra") {
    // Microsoft Graph unifiedRoleDefinition — POST to /roleManagement/directory/roleDefinitions
    return JSON.stringify({
      displayName: "Custom Least Privilege Role",
      description: "Generated by Least Privilege Studio",
      isEnabled: true,
      rolePermissions: [{ allowedResourceActions: ops.map(o => o.action), condition: null }],
      version: "1"
    }, null, 2);
  }
  return JSON.stringify({ properties: { roleName: "Custom Least Privilege Role", description: "Generated by Least Privilege Studio for Azure", assignableScopes: ["/subscriptions/<subscription-id>", "/subscriptions/<subscription-id>/resourceGroups/<resource-group>", "/providers/Microsoft.Management/managementGroups/<management-group-id>"], permissions: [{ actions: ops.filter(o => o.type === "action").map(o => o.action), notActions: [], dataActions: ops.filter(o => o.type === "dataAction").map(o => o.action), notDataActions: [] }] } }, null, 2) }

// ─── SEARCH SYNONYMS ────────────────────────────────────────────────────────
// Abbreviation → specific phrases matched as substrings of the type name.
// Only non-literal abbreviations (where the resource is named differently than
// the acronym); literal terms like "dns"/"sql" already match the name directly.
const ABBREV = {
  vm: ["virtual machine"], vms: ["virtual machine"],
  nic: ["network interface"], nsg: ["network security group"],
  vnet: ["virtual network"], aks: ["managed cluster", "kubernetes"],
  acr: ["container registr"], avd: ["host pool", "session host", "application group"],
  rg: ["resource group"], lb: ["load balancer"], kv: ["key vault"],
  pip: ["public ip"], k8s: ["kubernetes", "managed cluster"],
};

// Returns { filtered: categories, isPermSearch: bool, permQuery: string }
function searchMatch(query, categories) {
  if (!query.trim()) return { filtered: categories, isPermSearch: false, permQuery: "" };
  const q = query.toLowerCase().trim();
  
  // Prevent expanding all categories when the user is just typing the common prefix
  const isGeneric = /^(m|mi|mic|micr|micro|micros|microso|microsof|microsoft|microsoft\.)$/i.test(q);
  if (isGeneric) return { filtered: categories, isPermSearch: false, permQuery: "", isGeneric: true };

  // Mode 1: explicit permission path (contains / or microsoft.)
  if (q.includes("/") || q.includes("microsoft.")) {
    const f = categories.map(cat => ({ ...cat, providers: cat.providers.map(p => ({ ...p, types: p.types.filter(t => t.actions.some(a => a.ops.some(o => o.action.toLowerCase().includes(q)))) })).filter(p => p.types.length > 0) })).filter(c => c.providers.length > 0);
    return { filtered: f, isPermSearch: true, permQuery: q };
  }
  // Mode 2: plain-word search — a type matches if its OWN name matches
  // (word-boundary, abbreviation-aware) OR one of its operations matches (the
  // op tail, namespace stripped, so "deallocate"/"blob" find the right types).
  // Ignores the category/provider name and the namespace so results stay tight;
  // the tree renders matches collapsed with the matching level marked.
  const words = q.split(/\s+/).filter(Boolean);
  const esc = s => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const f = categories.map(cat => ({
    ...cat, providers: cat.providers.map(p => {
      const nsPrefix = (p.namespace + "/").toLowerCase();
      return {
        ...p, types: p.types.filter(t => {
          const nameHay = (t.name + " " + t.key).toLowerCase();
          const nameMatch = words.every(w => {
            if (new RegExp("\\b" + esc(w), "i").test(nameHay)) return true;
            if (ABBREV[w]) return ABBREV[w].some(ph => nameHay.includes(ph));
            return false;
          });
          if (nameMatch) return true;
          return t.actions.some(a => a.ops.some(o => {
            const l = o.action.toLowerCase();
            const tail = l.startsWith(nsPrefix) ? l.slice(nsPrefix.length) : l;
            return words.every(w => tail.includes(w));
          }));
        })
      };
    }).filter(p => p.types.length > 0)
  })).filter(c => c.providers.length > 0);
  return { filtered: f, isPermSearch: false, permQuery: "" };
}

// Highlight matching text in a string
function HL({ text, query }) {
  if (!query || query.length < 2) return text;
  const words = query.toLowerCase().split(/\s+/).filter(w => w.length >= 2);
  // Also add abbreviation expansions
  const allWords = [...words];
  for (const w of words) if (ABBREV[w]) allWords.push(...ABBREV[w].flatMap(ph => ph.split(/\s+/)).filter(s => s.length >= 2));
  if (!allWords.length) return text;
  const pat = allWords.map(w => w.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")).join("|");
  const splitRe = new RegExp(`(${pat})`, "gi");
  const testRe = new RegExp(`^(?:${pat})$`, "i"); // non-global: stateless, reliable per-part test
  const parts = text.split(splitRe);
  return parts.map((p, i) => testRe.test(p)
    ? <mark key={i} style={{ color: "#eaf7ff", fontWeight: 700, background: "rgba(79,195,247,0.28)", borderRadius: 3, padding: "0 3px", boxShadow: "0 0 0 1px rgba(79,195,247,0.4)" }}>{p}</mark>
    : p);
}

// ─── FRIENDLY NAMES ─────────────────────────────────────────────────────────
const FN = { "virtualMachines": "Virtual Machines", "virtualMachines/extensions": "VM Extensions", "virtualMachineScaleSets": "VM Scale Sets", "disks": "Managed Disks", "snapshots": "Disk Snapshots", "galleries": "Compute Galleries", "galleries/images/versions": "Gallery Image Versions", "availabilitySets": "Availability Sets", "virtualNetworks": "Virtual Networks", "virtualNetworks/subnets": "Subnets", "networkInterfaces": "Network Interfaces (NICs)", "publicIPAddresses": "Public IP Addresses", "networkSecurityGroups": "Network Security Groups (NSGs)", "loadBalancers": "Load Balancers", "applicationGateways": "Application Gateways", "routeTables": "Route Tables", "privateDnsZones": "Private DNS Zones", "privateEndpoints": "Private Endpoints", "bastionHosts": "Bastion Hosts", "natGateways": "NAT Gateways", "azureFirewalls": "Azure Firewalls", "virtualNetworkGateways": "VPN Gateways", "storageAccounts": "Storage Accounts", "storageAccounts/blobServices/containers": "Blob Containers", "storageAccounts/blobServices/containers/blobs": "Blobs (Data Plane)", "storageAccounts/fileServices/fileshares": "File Shares", "storageAccounts/queueServices/queues": "Queues", "storageAccounts/tableServices/tables": "Tables", "servers": "Servers", "servers/databases": "Databases", "servers/elasticPools": "Elastic Pools", "flexibleServers": "Flexible Servers", "databaseAccounts": "Cosmos DB Accounts", "sites": "Web Apps / Function Apps", "serverfarms": "App Service Plans", "staticSites": "Static Web Apps", "managedClusters": "AKS Clusters", "registries": "Container Registries", "containerGroups": "Container Instances", "vaults": "Key Vaults", "vaults/secrets": "Secrets", "vaults/keys": "Keys", "vaults/certificates": "Certificates", "hostpools": "Host Pools", "hostpools/sessionhosts": "Session Hosts", "applicationgroups": "Application Groups", "roleAssignments": "Role Assignments", "roleDefinitions": "Role Definitions", "policyAssignments": "Policy Assignments", "policyDefinitions": "Policy Definitions", "subscriptions/resourceGroups": "Resource Groups", "deployments": "Deployments", "userAssignedIdentities": "Managed Identities", "workspaces": "Workspaces", "components": "Application Insights" };
const PN = { "Microsoft.Compute": "Compute", "Microsoft.Network": "Network", "Microsoft.Storage": "Storage", "Microsoft.ClassicStorage": "Classic Storage", "Microsoft.NetApp": "NetApp Files", "Microsoft.Sql": "SQL", "Microsoft.DBforMySQL": "MySQL", "Microsoft.DBforPostgreSQL": "PostgreSQL", "Microsoft.DocumentDB": "Cosmos DB", "Microsoft.Cache": "Redis Cache", "Microsoft.DataFactory": "Data Factory", "Microsoft.Kusto": "Data Explorer", "Microsoft.Web": "App Service", "Microsoft.App": "Container Apps", "Microsoft.ApiManagement": "API Management", "Microsoft.ContainerService": "AKS", "Microsoft.ContainerRegistry": "Container Registry", "Microsoft.ContainerInstance": "Container Instances", "Microsoft.MachineLearningServices": "Machine Learning", "Microsoft.CognitiveServices": "Cognitive Services / OpenAI", "Microsoft.Search": "AI Search", "Microsoft.KeyVault": "Key Vault", "Microsoft.Security": "Security Center", "Microsoft.SecurityInsights": "Sentinel", "Microsoft.ManagedIdentity": "Managed Identity", "Microsoft.Insights": "Monitor / Insights", "Microsoft.OperationalInsights": "Log Analytics", "Microsoft.Authorization": "Authorization", "Microsoft.Resources": "Resource Manager", "Microsoft.CostManagement": "Cost Management", "Microsoft.Support": "Support", "Microsoft.Logic": "Logic Apps", "Microsoft.EventHub": "Event Hubs", "Microsoft.EventGrid": "Event Grid", "Microsoft.ServiceBus": "Service Bus", "Microsoft.Devices": "IoT Hub", "Microsoft.Databricks": "Databricks", "Microsoft.Synapse": "Synapse Analytics", "Microsoft.DesktopVirtualization": "Virtual Desktop", "Microsoft.RecoveryServices": "Recovery Services", "Microsoft.DevTestLab": "DevTest Labs", "Microsoft.Migrate": "Migrate" };
function fn(k) { return FN[k] || k.split("/").pop().replace(/([a-z])([A-Z])/g, "$1 $2").replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2").replace(/^./, s => s.toUpperCase()).trim() }
function pn(ns) { return PN[ns] || ns.replace("Microsoft.", "") }

// Display-time name cleanup: capitalize each word's first letter and fix known
// acronyms. Fixes auto-generated names like "capacity Reservation Groups" → "Capacity …",
// "skus" → "SKUs", "ssh Public Keys" → "SSH Public Keys". Runs on both datasets.
const ACRONYMS = { vm: "VM", vms: "VMs", ssh: "SSH", sku: "SKU", skus: "SKUs", ip: "IP", ips: "IPs", dns: "DNS", nsg: "NSG", nsgs: "NSGs", acr: "ACR", aks: "AKS", avd: "AVD", url: "URL", sql: "SQL", id: "ID", os: "OS", api: "API", db: "DB", cdn: "CDN", vpn: "VPN", waf: "WAF", ai: "AI", ml: "ML", iot: "IoT", b2c: "B2C", b2b: "B2B", oauth: "OAuth", sso: "SSO", mfa: "MFA", pim: "PIM", rbac: "RBAC", ad: "AD" };
function niceName(s) {
  if (!s) return s;
  return s.split(" ").map(w => {
    const low = w.toLowerCase();
    if (ACRONYMS[low]) return ACRONYMS[low];
    return w.charAt(0).toUpperCase() + w.slice(1);
  }).join(" ");
}

// Classify an operation into access level
function accessLevel(opAction) {
  const last = opAction.split("/").pop().toLowerCase();
  const prev = opAction.split("/").slice(-2, -1)[0]?.toLowerCase() || "";
  if (last === "read") return "Read";
  if (last === "write") return "Write";
  if (last === "delete") return "Delete";
  if (last === "action") {
    if (["join", "start", "stop", "deallocate", "poweroff", "restart", "reboot", "listkeys", "regeneratekey", "failover", "backup", "restore"].includes(prev)) return "Action";
    return "Action";
  }
  return "Action";
}

// Display name for an operation (returning full path including provider namespace)
function opShortName(action, ns) {
  return action;
}

// Render a resource path with its namespace prefix dimmed and the distinctive
// tail highlighted, e.g. "Microsoft.Compute/" (dim) + "availabilitySets" (bright).
// Makes it obvious exactly which resource the row grants access to.
function PathLabel({ prefix, tail, brightColor, size, highlightQuery }) {
  return <span style={{ fontFamily: "var(--m)", fontSize: size, wordBreak: "break-all" }}>
    <span style={{ color: "#566b85" }}>{highlightQuery ? <HL text={prefix} query={highlightQuery} /> : prefix}</span>
    <span style={{ color: brightColor, fontWeight: 600 }}>{highlightQuery ? <HL text={tail} query={highlightQuery} /> : tail}</span>
  </span>;
}

// Render a full action path with the shared "<namespace>/<type>/" prefix dimmed
// and the distinctive tail highlighted — keeps the complete string, cuts the noise.
function OpSplit({ action, ns, typeKey, selected, highlightQuery }) {
  const prefix = typeKey ? `${ns}/${typeKey}/` : `${ns}/`;
  let head, tail;
  if (action.startsWith(prefix)) { head = prefix; tail = action.slice(prefix.length); }
  else { const i = action.lastIndexOf("/"); head = i >= 0 ? action.slice(0, i + 1) : ""; tail = i >= 0 ? action.slice(i + 1) : action; }
  return <>{head && <span style={{ color: "#566b85" }}>{head}</span>}<span style={{ color: selected ? "#eaf2ff" : "#c8d6e5", fontWeight: 500 }}>{highlightQuery ? <HL text={tail} query={highlightQuery} /> : tail}</span></>;
}

// ─── DATA ───────────────────────────────────────────────────────────────────
function useData(dataset) {
  const [c, sC] = useState([]); const [r, sR] = useState([]); const [m, sM] = useState(null); const [l, sL] = useState(true); const [d, sD] = useState(false);
  const [opsDescMap, setOpsDescMap] = useState(null);
  const opsIndexLoading = useRef(false);
  // File prefix per dataset — Azure files are unprefixed, Entra files use "entra-".
  const pre = dataset === "entra" ? "entra-" : "";

  useEffect(() => {
    let cancelled = false;
    sL(true); setOpsDescMap(null); opsIndexLoading.current = false;
    (async () => {
      // Use relative path so it works with any base path
      const base = (import.meta.env.BASE_URL || "/").replace(/\/?$/, "/");
      const f = p => fetch(`${base}data/${p}`).then(x => x.ok ? x.json() : null);
      try {
        const [a, b, d2] = await Promise.allSettled([f(`${pre}ui-structure.json`), f(`${pre}roles.json`), f(`${pre}metadata.json`)]);
        if (cancelled) return;
        const cv = a.status === "fulfilled" && a.value, rv = b.status === "fulfilled" && b.value;
        if (cv?.length && rv?.length) { sC(cv); sR(rv); sM(d2.status === "fulfilled" && d2.value || null); sD(false) }
        else if (dataset === "entra") { sD(false); sC([]); sR([]); sM(null) }
        else { sD(true); sC(DC); sR(DR) }
      } catch { if (!cancelled) { if (dataset === "entra") { sC([]); sR([]) } else { sD(true); sC(DC); sR(DR) } } }
      if (!cancelled) sL(false);
    })();
    return () => { cancelled = true };
  }, [dataset]);

  const loadOpsIndex = useCallback(async () => {
    if (opsDescMap !== null || opsIndexLoading.current) return;
    opsIndexLoading.current = true;
    try {
      const base = (import.meta.env.BASE_URL || "/").replace(/\/?$/, "/");
      const data = await fetch(`${base}data/${pre}operations-index.json`).then(x => x.ok ? x.json() : null);
      if (Array.isArray(data)) {
        const map = {};
        for (const { action, description } of data) map[action] = description;
        setOpsDescMap(map);
      } else {
        setOpsDescMap({});
      }
    } catch { setOpsDescMap({}) }
  }, [opsDescMap, pre]);

  return { categories: c, roles: r, meta: m, loading: l, isDemo: d, opsDescMap, loadOpsIndex }
}

// ─── STYLES ─────────────────────────────────────────────────────────────────
const AC = {
  // Azure RBAC categories
  "Compute": "#e94560", "Networking": "#4fc3f7", "Storage": "#0f9b58", "Databases": "#5c6bc0", "Web + Serverless": "#ef5350", "Containers": "#29b6f6", "AI + Machine Learning": "#ce93d8", "Security": "#f5a623", "Identity": "#ff7043", "DevOps": "#8d6e63", "Monitor": "#fdd835", "Management + Governance": "#78909c", "Integration": "#26a69a", "Analytics": "#ab47bc", "Desktop Virtualization": "#7e57c2", "Internet of Things": "#00acc1", "Backup + Recovery": "#66bb6a", "Migration": "#a1887f", "Other": "#90a4ae",
  // Entra ID categories
  "Users": "#ff7043", "Groups": "#66bb6a", "Applications": "#ab47bc", "Devices": "#29b6f6", "Conditional Access & Policies": "#f5a623", "Roles & RBAC": "#e94560", "Identity Governance": "#26a69a", "Agent Identity": "#ce93d8", "External Identities": "#4fc3f7", "Organization": "#78909c", "Hybrid & Provisioning": "#8d6e63", "Monitoring & Reports": "#fdd835", "Custom Security Attributes": "#5c6bc0", "Verifiable Credentials": "#7e57c2", "Recovery & Lockbox": "#a1887f"
};
const ac = c => AC[c] || "#4fc3f7";
const LVLC = { "Read": "#4fc3f7", "Write": "#f5a623", "Delete": "#e94560", "Action": "#ab47bc" };

// ─── COMPONENTS ─────────────────────────────────────────────────────────────
function Meter({ v }) { const p = Math.round(v * 100); const grad = p === 100 ? "linear-gradient(90deg,#0f9b58,#4fc3f7)" : p >= 80 ? "linear-gradient(90deg,#f5a623,#fdd835)" : "linear-gradient(90deg,#e94560,#f5a623)"; const c = p === 100 ? "#4fc3f7" : p >= 80 ? "#fdd835" : "#f5a623"; return <div style={{ display: "flex", alignItems: "center", gap: 10 }}><div style={{ flex: 1, height: 6, background: "#1e1e3a", borderRadius: 3, overflow: "hidden" }}><div style={{ width: `${p}%`, height: "100%", background: grad, borderRadius: 3, transition: "width 0.4s" }} /></div><span style={{ fontFamily: "var(--m)", fontSize: 13, color: c, minWidth: 44, textAlign: "right" }}>{p}%</span></div> }
function OB({ op, onRemove }) { const d = op.type === "dataAction"; return <div style={{ display: "flex", alignItems: "center", gap: 8, padding: "5px 10px", background: d ? "rgba(245,166,35,0.08)" : "rgba(79,195,247,0.08)", border: `1px solid ${d ? "rgba(245,166,35,0.2)" : "rgba(79,195,247,0.15)"}`, borderRadius: 6, fontFamily: "var(--m)", fontSize: 11.5, color: "#c8d6e5" }}><span style={{ fontSize: 9, fontWeight: 700, padding: "2px 6px", borderRadius: 3, textTransform: "uppercase", letterSpacing: "0.05em", background: d ? "rgba(245,166,35,0.2)" : "rgba(79,195,247,0.15)", color: d ? "#f5a623" : "#4fc3f7" }}>{d ? "Data" : "Action"}</span><span style={{ wordBreak: "break-all", flex: 1 }}>{op.action}</span>{onRemove && <button onClick={() => onRemove(op.action)} style={{ background: "none", border: "none", color: "#6b7c93", cursor: "pointer", fontSize: 16, padding: "0 2px", lineHeight: 1, flexShrink: 0, opacity: 0.6 }} title="Remove this permission">×</button>}</div> }
function RoleCard({ role, total, open, toggle }) { const cc = role.coverage === 1 ? "#0f9b58" : role.coverage >= 0.8 ? "#f5a623" : "#e94560"; return <div onClick={toggle} className="role-card" style={{ background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12, padding: 16, cursor: "pointer", borderLeft: `3px solid ${cc}`, transition: "all 0.2s", boxShadow: "0 2px 12px rgba(0,0,0,0.2)" }}><div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 6 }}><div style={{ flex: 1 }}><div style={{ fontSize: 15, fontWeight: 600, color: "#e8ecf1", marginBottom: 2 }}>{role.name}</div><div style={{ fontSize: 11, color: "#647a94", fontFamily: "var(--m)", marginBottom: 3 }}>{role.id}</div><div style={{ fontSize: 12, color: "#6b7c93", lineHeight: 1.4 }}>{role.description}</div></div><span style={{ fontSize: 16, color: "#6b7c93", marginLeft: 12, transform: open ? "rotate(180deg)" : "none", transition: "transform 0.2s" }}>▾</span></div><div style={{ display: "flex", gap: 14, marginTop: 8, flexWrap: "wrap", fontSize: 12 }}><span style={{ color: "#8899aa" }}>Coverage: <span style={{ color: cc, fontWeight: 700 }}>{role.coveredCount}/{total}</span></span>{role.missedCount > 0 && <span style={{ color: "#e94560" }}>Missing: {role.missedCount}</span>}<span style={{ color: "#6b7c93" }}>~{role.est} total actions</span></div><div style={{ marginTop: 8 }}><Meter v={role.coverage} /></div>{open && <div style={{ marginTop: 14, paddingTop: 14, borderTop: "1px solid rgba(255,255,255,0.06)" }}>{role.missedCount > 0 && <div style={{ marginBottom: 12 }}><div style={{ fontSize: 12, fontWeight: 600, color: "#e94560", marginBottom: 8 }}>⚠ Not covered:</div><div style={{ display: "flex", flexDirection: "column", gap: 4 }}>{role.missedOps.map((o, i) => <OB key={i} op={o} />)}</div></div>}<div style={{ fontSize: 12, color: "#6b7c93", lineHeight: 1.6 }}>This role grants ~<b style={{ color: "#c8d6e5" }}>{role.est}</b> actions. You selected <b style={{ color: "#c8d6e5" }}>{total}</b>. Review whether the extra actions are acceptable.</div></div>}</div> }


// AWS-style Action Group (Read, Write, Delete, Action)
const ActionGroup = React.memo(function ActionGroup({ label, ops, ns, typeKey, sel, onToggle, actionFilter, color, highlightQuery }) {
  const [userClosed, setUC] = useState(false);
  const [userOpened, setUO] = useState(false);
  const selCount = ops.filter(op => sel[op.action]).length;
  const afWords = actionFilter ? actionFilter.split(/\s+/).filter(Boolean) : [];
  const filtered = afWords.length ? ops.filter(op => { const p = opShortName(op.action, ns).toLowerCase(); return afWords.every(w => p.includes(w)) }) : ops;
  // Default open if filter is active, but respect user toggle
  const isOpen = userClosed ? false : userOpened ? true : (afWords.length > 0);
  if (afWords.length > 0 && !filtered.length) return null;

  const toggle = () => { if (isOpen) { setUC(true); setUO(false) } else { setUO(true); setUC(false) } };

  return <div style={{ marginBottom: 4 }}>
    <button onClick={toggle} style={{ display: "flex", alignItems: "center", gap: 8, padding: "6px 0", background: "none", border: "none", cursor: "pointer", fontFamily: "inherit", width: "100%" }}>
      <span style={{ fontSize: 11, color: "#6b7c93", transform: isOpen ? "rotate(90deg)" : "none", transition: "transform 0.15s" }}>▸</span>
      <span style={{ fontSize: 13, fontWeight: 600, color }}>{label}</span>
      <span style={{ fontSize: 12, color: "#6b7c93" }}>({selCount > 0 ? <span style={{ color }}>selected {selCount}/</span> : ""}{afWords.length ? filtered.length : ops.length})</span>
    </button>
    {isOpen && <div style={{ paddingLeft: 20, display: "flex", flexDirection: "column", gap: 2, marginBottom: 8 }}>
      <label style={{ display: "flex", alignItems: "center", gap: 8, padding: "4px 0", cursor: "pointer", fontSize: 12, color: "#8899aa" }}>
        <input type="checkbox" checked={selCount === ops.length && ops.length > 0} onChange={() => {
          const allOn = selCount === ops.length; const u = {}; for (const op of ops) u[op.action] = !allOn; onToggle(u);
        }} style={{ accentColor: color }} />
        All {label.toLowerCase()} actions
      </label>
      {filtered.map(op => (
        <label key={op.action} style={{ display: "flex", alignItems: "center", gap: 8, padding: "3px 0", cursor: "pointer" }}>
          <input type="checkbox" checked={!!sel[op.action]} onChange={() => onToggle({ [op.action]: !sel[op.action] })} style={{ accentColor: color }} />
          <span style={{ fontFamily: "var(--m)", fontSize: 11.5, wordBreak: "break-all" }}><OpSplit action={op.action} ns={ns} typeKey={typeKey} selected={!!sel[op.action]} highlightQuery={highlightQuery} /></span>
          {op.type === "dataAction" && <span style={{ fontSize: 9, padding: "1px 5px", borderRadius: 3, background: "rgba(245,166,35,0.15)", color: "#f5a623", fontWeight: 600 }}>Data</span>}
        </label>
      ))}
    </div>}
  </div>;
});

// ─── ROLE PICKER ────────────────────────────────────────────────────────────
// Fast role resolution: pre-build an index of all operations, then match
function useOpIndex(categories) {
  return useMemo(() => {
    const actions = []; // {action, type}
    const actionSet = new Set();
    for (const cat of categories) for (const p of cat.providers) for (const t of p.types) for (const a of t.actions) for (const op of a.ops) {
      if (!actionSet.has(op.action)) { actionSet.add(op.action); actions.push(op); }
    }
    return actions;
  }, [categories]);
}

function resolveRoleFast(role, allOps) {
  const matched = new Set();
  // Pre-check simple wildcards first (fast path)
  const hasWildAll = role.actions.includes("*");
  const hasWildRead = role.actions.includes("*/read");

  for (const op of allOps) {
    const pool = op.type === "dataAction" ? (role.dataActions || []) : (role.actions || []);
    const not = op.type === "dataAction" ? (role.notDataActions || []) : (role.notActions || []);

    // Fast path for common wildcards
    let match = false;
    if (op.type !== "dataAction") {
      if (hasWildAll) match = true;
      else if (hasWildRead && op.action.endsWith("/read")) match = true;
    }
    if (!match) match = pool.some(p => mw(p, op.action));
    if (!match) continue;
    if (not.some(p => mw(p, op.action))) continue;
    matched.add(op.action);
  }
  return matched;
}

function RoleImport({ roles, allOps, onApply, appliedRoles, onRemove }) {
  const [open, setOpen] = useState(false);
  const [query, setQ] = useState("");
  const ref = useRef(null);

  useEffect(() => {
    const h = e => { if (ref.current && !ref.current.contains(e.target)) setOpen(false) };
    document.addEventListener("mousedown", h);
    return () => document.removeEventListener("mousedown", h);
  }, []);

  const filtered = useMemo(() => {
    if (!query.trim()) return []; // Show nothing until user types
    const q = query.toLowerCase();
    return roles.filter(r => r.name.toLowerCase().includes(q) || r.description.toLowerCase().includes(q));
  }, [roles, query]);

  return (
    <div style={{ display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 14, flexWrap: "wrap" }}>
      {/* Applied role tags */}
      {appliedRoles.map(r => (
        <span key={r.id} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "5px 10px", borderRadius: 6, fontSize: 12, fontWeight: 500, background: "rgba(79,195,247,0.1)", border: "1px solid rgba(79,195,247,0.25)", color: "#4fc3f7" }}>
          {r.name}
          <button onClick={() => onRemove(r)} style={{ background: "none", border: "none", color: "#4fc3f7", cursor: "pointer", fontSize: 14, padding: 0, lineHeight: 1, opacity: 0.7 }}>×</button>
        </span>
      ))}

      {/* Import button + dropdown */}
      <div ref={ref} style={{ position: "relative" }}>
        <button onClick={() => setOpen(!open)} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 14px", borderRadius: 8, fontSize: 12, fontWeight: 500, cursor: "pointer", fontFamily: "inherit", background: open ? "rgba(171,71,188,0.12)" : "rgba(255,255,255,0.05)", border: `1px solid ${open ? "rgba(171,71,188,0.35)" : "rgba(255,255,255,0.1)"}`, color: open ? "#ce93d8" : "#7a8fa8", transition: "all 0.15s" }}>
          <span style={{ fontSize: 13 }}>+</span> Import from role
        </button>

        {open && (
          <div style={{ position: "absolute", top: "100%", left: 0, zIndex: 50, marginTop: 6, width: 380, background: "#1a1a2e", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 10, boxShadow: "0 8px 32px rgba(0,0,0,0.5)", overflow: "hidden" }}>
            <div style={{ padding: "10px 12px 8px", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
              <input
                value={query} autoFocus
                onChange={e => setQ(e.target.value)}
                placeholder="Type to search roles..."
                style={{ width: "100%", boxSizing: "border-box", padding: "8px 12px", background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 6, color: "#e8ecf1", fontSize: 12.5, fontFamily: "inherit", outline: "none" }}
                onKeyDown={e => { if (e.key === "Escape") { setOpen(false); setQ("") } }}
              />
            </div>
            <div style={{ maxHeight: 300, overflowY: "auto" }}>
              {!query.trim() && <div style={{ padding: "16px 14px", fontSize: 12, color: "#647a94", textAlign: "center" }}>Start typing to search {roles.length} built-in roles</div>}
              {filtered.map(r => {
                const already = appliedRoles.some(a => a.id === r.id);
                return (
                  <button key={r.id}
                    onClick={() => { if (!already) { onApply(r); setQ(""); setOpen(false) } }}
                    style={{ width: "100%", display: "flex", flexDirection: "column", gap: 2, padding: "9px 14px", background: already ? "rgba(79,195,247,0.06)" : "transparent", border: "none", borderBottom: "1px solid rgba(255,255,255,0.03)", cursor: already ? "default" : "pointer", fontFamily: "inherit", textAlign: "left", opacity: already ? 0.5 : 1 }}
                    onMouseEnter={e => { if (!already) e.currentTarget.style.background = "rgba(255,255,255,0.05)" }}
                    onMouseLeave={e => { e.currentTarget.style.background = already ? "rgba(79,195,247,0.06)" : "transparent" }}
                  >
                    <div style={{ fontSize: 13, fontWeight: 500, color: already ? "#6b7c93" : "#e8ecf1" }}>{r.name}{already && " ✓"}</div>
                    <div style={{ fontSize: 11, color: "#647a94", lineHeight: 1.3 }}>{r.description}</div>
                  </button>
                );
              })}
              {query.trim() && !filtered.length && <div style={{ padding: "16px 14px", fontSize: 12, color: "#647a94", textAlign: "center" }}>No roles found</div>}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function CustomRoleImport({ allOps, onImport }) {
  const [open, setOpen] = useState(false);
  const [json, setJson] = useState("");
  const [error, setErr] = useState("");
  const ref = useRef(null);
  useEffect(() => { const h = e => { if (ref.current && !ref.current.contains(e.target)) setOpen(false) }; document.addEventListener("mousedown", h); return () => document.removeEventListener("mousedown", h) }, []);

  const doImport = () => {
    try {
      const parsed = JSON.parse(json);
      // Support both formats: {properties:{permissions:[{actions}]}} and {Actions:[]}
      let actions = [], dataActions = [], notActions = [];
      if (parsed.rolePermissions?.[0]) {
        // Entra ID: Microsoft Graph unifiedRoleDefinition
        actions = parsed.rolePermissions.flatMap(p => p.allowedResourceActions || []);
        notActions = parsed.rolePermissions.flatMap(p => p.excludedResourceActions || []);
      } else if (parsed.properties?.permissions?.[0]) {
        actions = parsed.properties.permissions[0].actions || [];
        dataActions = parsed.properties.permissions[0].dataActions || [];
        notActions = parsed.properties.permissions[0].notActions || [];
      } else {
        actions = parsed.Actions || parsed.actions || [];
        dataActions = parsed.DataActions || parsed.dataActions || [];
        notActions = parsed.NotActions || [];
      }
      if (!actions.length && !dataActions.length) { setErr("No actions found in JSON"); return }
      const role = { name: parsed.displayName || parsed.properties?.roleName || parsed.Name || "Custom Role", actions, notActions, dataActions, notDataActions: parsed.properties?.permissions?.[0]?.notDataActions || parsed.NotDataActions || [] };
      onImport(role);
      setOpen(false); setJson(""); setErr("");
    } catch (e) { setErr("Invalid JSON: " + e.message) }
  };

  return <div ref={ref} style={{ position: "relative" }}>
    <button onClick={() => setOpen(!open)} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "6px 14px", borderRadius: 8, fontSize: 12, fontWeight: 500, cursor: "pointer", fontFamily: "inherit", background: open ? "rgba(79,195,247,0.12)" : "rgba(255,255,255,0.05)", border: `1px solid ${open ? "rgba(79,195,247,0.35)" : "rgba(255,255,255,0.1)"}`, color: open ? "#4fc3f7" : "#7a8fa8", transition: "all 0.15s" }}>
      <span style={{ fontSize: 13 }}>+</span> Import custom JSON
    </button>
    {open && <div style={{ position: "absolute", top: "100%", left: 0, zIndex: 50, marginTop: 6, width: 400, background: "#1a1a2e", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 10, boxShadow: "0 8px 32px rgba(0,0,0,0.5)", padding: 14 }}>
      <div style={{ fontSize: 12, color: "#8899aa", marginBottom: 8 }}>Paste a custom role JSON definition</div>
      <textarea value={json} onChange={e => { setJson(e.target.value); setErr("") }} placeholder='{"properties":{"permissions":[{"actions":["Microsoft.Compute/virtualMachines/read"]}]}}' style={{ width: "100%", boxSizing: "border-box", height: 120, padding: 10, background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 6, color: "#e8ecf1", fontSize: 11, fontFamily: "var(--m)", outline: "none", resize: "vertical" }} />
      {error && <div style={{ fontSize: 11, color: "#e94560", marginTop: 6 }}>{error}</div>}
      <button onClick={doImport} style={{ marginTop: 8, padding: "6px 16px", borderRadius: 6, fontSize: 12, fontWeight: 600, cursor: "pointer", background: "rgba(79,195,247,0.15)", border: "1px solid rgba(79,195,247,0.3)", color: "#4fc3f7", fontFamily: "inherit" }}>Import</button>
    </div>}
  </div>;
}
const NAV_TABS = [
  { id: "studio", label: "Build" },
  { id: "iac", label: "From IaC", azureOnly: true },
  { id: "roles", label: "Browse roles" },
  { id: "operations", label: "Browse operations" },
];

function NavBar({ view, setView, dataset }) {
  const tabs = NAV_TABS.filter(t => !t.azureOnly || dataset === "azure");
  return (
    <nav style={{ display: "flex", gap: 2, borderBottom: "1px solid rgba(255,255,255,0.07)", marginBottom: 0 }}>
      {tabs.map(tab => (
        <button
          key={tab.id}
          onClick={() => setView(tab.id)}
          className="nav-tab"
          style={{
            padding: "10px 20px",
            background: view === tab.id ? "rgba(79,195,247,0.07)" : "none",
            border: "none",
            borderBottom: view === tab.id ? "2px solid #4fc3f7" : "2px solid transparent",
            borderRadius: "6px 6px 0 0",
            color: view === tab.id ? "#4fc3f7" : "#6b7c93",
            fontFamily: "inherit", fontSize: 13, fontWeight: view === tab.id ? 600 : 400,
            cursor: "pointer", transition: "all 0.15s", outline: "none"
          }}
        >
          {tab.label}
        </button>
      ))}
    </nav>
  );
}

export default function App() {
  // Dataset: "azure" (default) | "entra". Shareable via #entra URL hash.
  const [dataset, setDataset] = useState(() => (typeof window !== "undefined" && window.location.hash.replace("#", "") === "entra") ? "entra" : "azure");
  const { categories, roles, meta, loading, isDemo, opsDescMap, loadOpsIndex } = useData(dataset);
  const [view, setView] = useState("studio");

  const handleSetView = useCallback((v) => {
    setView(v);
    if (v === "operations") loadOpsIndex();
  }, [loadOpsIndex]);
  const allOps = useOpIndex(categories);
  // sel: { "Microsoft.Compute/virtualMachines/read": true }
  const [sel, setSel] = useState({});
  const [appliedRoles, setAR] = useState([]);
  const [openCat, setOC] = useState(null);
  const [openProv, setOP] = useState({});
  const [openRT, setORT] = useState(null); // only one RT open at a time (like AWS)
  const [openRole, setOR] = useState(null);
  const [showJSON, setSJ] = useState(false);
  const [copied, setCP] = useState(false);
  const [filterInput, setFI] = useState("");
  const [filter, setF] = useState("");
  const [actionFilter, setAF] = useState("");
  const rRef = useRef(null);
  const debounceRef = useRef(null);
  const handleSearch = useCallback(v => {
    setFI(v);
    if (debounceRef.current) clearTimeout(debounceRef.current);
    // Immediate for 0 length (clearing) or 3+ chars, debounce for 1-2 chars
    if (!v.trim() || v.trim().length >= 3) { setF(v) }
    else { debounceRef.current = setTimeout(() => setF(v), 400) }
  }, []);

  const toggleOps = useCallback((updates) => {
    startTransition(() => {
      setSel(prev => {
        const next = { ...prev };
        for (const [action, val] of Object.entries(updates)) {
          if (val) next[action] = true;
          else delete next[action];
        }
        return next;
      });
    });
  }, []);

  // Apply a built-in role: resolve its wildcards and select all matching operations
  const [importing, setImporting] = useState(false);
  const [importMsg, setImportMsg] = useState("");
  const applyRole = useCallback((role) => {
    const isBroad = role.actions.includes("*") || role.actions.includes("*/read");
    setImporting(true);
    setImportMsg(isBroad ? "Importing broad role — this may take a moment..." : "Importing role permissions...");
    setAR(prev => [...prev, role]);
    // Process in next frame to show loading state
    requestAnimationFrame(() => {
      const ops = resolveRoleFast(role, allOps);
      const newSel = {};
      for (const a of ops) newSel[a] = true;
      startTransition(() => { setSel(prev => ({ ...prev, ...newSel })) });
      setImporting(false);
      setImportMsg("");
    });
  }, [allOps]);

  const removeRole = useCallback((role) => {
    setAR(prev => prev.filter(r => r.id !== role.id));
  }, []);

  const addRoleToStudio = useCallback((role) => {
    applyRole(role);
    setView("studio");
  }, [applyRole]);

  const addOpToStudio = useCallback((op) => {
    toggleOps({ [op.action]: true });
    setView("studio");
  }, [toggleOps]);

  // Apply a batch of actions derived from an IaC template. Stay on the IaC tab so
  // the user can paste more templates and keep accumulating — the sticky builder
  // bar shows the running total and the jump to role + JSON.
  const applyIaC = useCallback((actions) => {
    if (!actions?.length) return;
    const updates = {};
    for (const a of actions) updates[a] = true;
    toggleOps(updates);
  }, [toggleOps]);

  const applyCustomRole = useCallback((role) => {
    const ops = resolveRoleFast(role, allOps);
    startTransition(() => { setSel(prev => { const n = { ...prev }; for (const a of ops) n[a] = true; return n }) });
    setAR(prev => [...prev, { ...role, id: "custom-" + Date.now() }]);
  }, [allOps]);

  // Collect selected operations with their type info
  // Fast: use pre-built index instead of scanning all categories
  const sOps = useMemo(() => allOps.filter(op => sel[op.action]), [sel, allOps]);

  const sCount = Object.keys(sel).length;


  // Defer heavy role matching so UI stays responsive
  const deferredOps = useDeferredValue(sOps);
  const rolesStale = deferredOps !== sOps;
  const mRoles = useMemo(() => findRoles(roles, deferredOps), [roles, deferredOps]);
  const cJSON = useMemo(() => mkJSON(sOps, dataset), [sOps, dataset]);
  const clr = useCallback(() => { setSel({}); setOR(null); setSJ(false); setAR([]); setFI(""); setF("") }, []);
  // Switch dataset: selections don't carry across (Azure actions don't exist in Entra), so wipe state.
  const switchDataset = useCallback((ds) => {
    if (ds === dataset) return;
    setSel({}); setOR(null); setSJ(false); setAR([]); setFI(""); setF(""); setAF(""); setOC(null); setOP({}); setORT(null); setView("studio");
    setDataset(ds);
    if (typeof window !== "undefined") { if (ds === "entra") window.location.hash = "entra"; else history.replaceState(null, "", window.location.pathname + window.location.search); }
  }, [dataset]);
  const copy = useCallback(txt => { navigator.clipboard.writeText(txt); setCP(true); setTimeout(() => setCP(false), 2000) }, []);
  const removeOp = useCallback(action => { startTransition(() => { setSel(prev => { const n = { ...prev }; delete n[action]; return n }) }) }, []);

  // Search
  const { filtered: searchFiltered, isPermSearch, permQuery, isGeneric } = useMemo(() => searchMatch(filter, categories), [filter, categories]);
  const isSearch = filter.trim().length > 0 && !isGeneric;
  const sorted = useMemo(() => searchFiltered.map(cat => ({ ...cat, providers: cat.providers.map(p => ({ ...p, types: [...p.types] })) })), [searchFiltered]);

  // When searching, compute which resource types matched via operation paths (not just name)
  // These should auto-expand with the search term as action filter
  // No auto-scroll — user scrolls to results manually

  // Group a resource type's operations by access level
  function groupByLevel(rt, ns) {
    const groups = { Read: [], Write: [], Delete: [], Action: [] };
    for (const a of rt.actions) for (const op of a.ops) {
      const lvl = accessLevel(op.action);
      groups[lvl].push(op);
    }
    return Object.entries(groups).filter(([, ops]) => ops.length > 0);
  }

  function hasCatSel(cat) { return cat.providers.some(p => p.types.some(t => t.actions.some(a => a.ops.some(op => sel[op.action])))) }
  function hasProvSel(p) { return p.types.some(t => t.actions.some(a => a.ops.some(op => sel[op.action]))) }
  function hasRTSel(p, t) { return t.actions.some(a => a.ops.some(op => sel[op.action])) }
  function rtSelCount(t) { let c = 0; for (const a of t.actions) for (const op of a.ops) if (sel[op.action]) c++; return c }

  if (loading) return <div style={{ ...ROOT, display: "flex", alignItems: "center", justifyContent: "center" }}><div style={{ color: "#6b7c93" }}>Loading...</div></div>;

  return (
    <div style={ROOT}>
      <style>{`*{box-sizing:border-box}html,body,#root{margin:0;padding:0}.cat-row:hover{background:rgba(255,255,255,0.04)!important}.prov-row:hover{background:rgba(255,255,255,0.04)!important}.rt-row:hover{background:rgba(255,255,255,0.06)!important}.role-card:hover{background:rgba(255,255,255,0.05)!important;transform:translateY(-1px);box-shadow:0 4px 20px rgba(0,0,0,0.3)!important}.nav-tab:hover{color:#a8c8e8!important}`}</style>
      <link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet" />
      <header style={{ padding: "52px 24px 20px", maxWidth: 960, margin: "0 auto" }}>
        <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 14 }}>
          <img src={`${import.meta.env.BASE_URL}icon.png`} alt="" style={{ width: 46, height: 46, borderRadius: 12, boxShadow: "0 0 28px rgba(79,195,247,0.22), 0 4px 14px rgba(0,0,0,0.5)", flexShrink: 0 }} />
          <h1 style={{ fontSize: 30, fontWeight: 700, margin: 0, letterSpacing: "-0.02em", lineHeight: 1.15, background: "linear-gradient(95deg, #e8f0ff 15%, #4fc3f7 55%, #b39dda 100%)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" }}>Least Privilege Studio</h1>
        </div>
        <p style={{ fontSize: 14, color: "#7a8fa8", margin: "0 0 5px", fontWeight: 500 }}>Build least-privilege roles for <b style={{ color: dataset === "azure" ? "#4fc3f7" : "#7a8fa8", fontWeight: 600 }}>Azure RBAC</b> and <b style={{ color: dataset === "entra" ? "#b39dda" : "#7a8fa8", fontWeight: 600 }}>Entra ID</b> — pick a scope below.</p>
        <p style={{ fontSize: 13, color: "#647a94", margin: 0, lineHeight: 1.6, maxWidth: 600 }}>Select resources and actions you need. Get least-privilege built-in roles and custom role definitions.</p>
        {/* Scope selector — the toggle that swaps the whole dataset */}
        <div style={{ display: "flex", alignItems: "center", gap: 12, marginTop: 16, flexWrap: "wrap" }}>
          <span style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", color: "#647a94" }}>Scope</span>
          <div style={{ display: "inline-flex", background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 12, padding: 4, gap: 3 }}>
            {[{ id: "azure", label: "Azure RBAC", c: "#4fc3f7" }, { id: "entra", label: "Entra ID", c: "#b39dda" }].map(o => {
              const on = dataset === o.id;
              return <button key={o.id} onClick={() => switchDataset(o.id)} style={{ display: "inline-flex", alignItems: "center", gap: 9, padding: "10px 20px", borderRadius: 9, border: "none", cursor: "pointer", fontFamily: "inherit", fontSize: 14, fontWeight: on ? 700 : 500, background: on ? `${o.c}22` : "transparent", color: on ? o.c : "#8899aa", boxShadow: on ? `0 0 0 1px ${o.c}55, 0 2px 14px ${o.c}22` : "none", transition: "all 0.15s" }}>
                <span style={{ width: 8, height: 8, borderRadius: 4, background: o.c, opacity: on ? 1 : 0.35, transition: "opacity 0.15s" }} />
                {o.label}
              </button>;
            })}
          </div>
        </div>
        {isDemo && <div style={{ marginTop: 10, padding: "8px 14px", borderRadius: 8, fontSize: 12, background: "rgba(245,166,35,0.1)", border: "1px solid rgba(245,166,35,0.2)", color: "#f5a623" }}>⚠ Demo data. Run <code style={{ background: "rgba(0,0,0,0.2)", padding: "1px 5px", borderRadius: 3 }}>npm run sync:all</code> to load all Azure RBAC data.</div>}
        {dataset === "entra" && !roles.length && !loading && <div style={{ marginTop: 10, padding: "8px 14px", borderRadius: 8, fontSize: 12, background: "rgba(245,166,35,0.1)", border: "1px solid rgba(245,166,35,0.2)", color: "#f5a623" }}>⚠ No Entra data. Run <code style={{ background: "rgba(0,0,0,0.2)", padding: "1px 5px", borderRadius: 3 }}>npm run sync:entra && node scripts/build-entra.js</code>.</div>}
        {meta && <div style={{ marginTop: 12, display: "flex", gap: 6, flexWrap: "wrap" }}>{[`${meta.roleCount} roles`, `${meta.operationCount} operations`, `${meta.categoryCount} categories`, `Synced ${new Date(meta.lastSync).toLocaleDateString()}`].map((t, i) => <span key={i} style={{ fontSize: 11, color: "#647a94", padding: "2px 9px", borderRadius: 4, background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.06)" }}>{t}</span>)}</div>}
      </header>

      <div style={{ height: 1, background: "linear-gradient(90deg, transparent, rgba(79,195,247,0.25), rgba(171,71,188,0.18), transparent)", maxWidth: 960, margin: "0 auto" }} />
      <div style={{ maxWidth: 960, margin: "0 auto", padding: "0 24px 4px" }}>
        <NavBar view={view} setView={handleSetView} dataset={dataset} />
      </div>

      {view === "iac" && dataset === "azure" && (
        <div style={{ maxWidth: 960, margin: "0 auto", padding: "24px 24px 60px" }}>
          <IaCPanel allOps={allOps} onApply={applyIaC} />
        </div>
      )}
      {view === "roles" && (
        <div style={{ maxWidth: 960, margin: "0 auto", padding: "24px 24px 60px" }}>
          <RolesCatalog roles={roles} onAddToStudio={addRoleToStudio} />
        </div>
      )}
      {view === "operations" && (
        <div style={{ maxWidth: 960, margin: "0 auto", padding: "24px 24px 60px" }}>
          {opsDescMap === null
            ? <div style={{ padding: 24, textAlign: "center", fontSize: 13, color: "#6b7c93" }}>Loading operations index…</div>
            : <OperationsCatalog categories={categories} roles={roles} opsDescMap={opsDescMap} onAddOpToStudio={addOpToStudio} onAddRoleToStudio={addRoleToStudio} />
          }
        </div>
      )}
      {view === "studio" && <div style={{ maxWidth: 960, margin: "0 auto", padding: "16px 24px" }}>
        {/* Search */}
        <div style={{ position: "relative", marginBottom: 12 }}>
          <input value={filterInput} onChange={e => handleSearch(e.target.value)} placeholder="Search resources... e.g. virtual machine, blob, aks, /start" style={{ width: "100%", boxSizing: "border-box", padding: "13px 16px 13px 46px", background: "rgba(255,255,255,0.04)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 12, color: "#e8ecf1", fontSize: 14, fontFamily: "inherit", outline: "none", transition: "border-color 0.2s, box-shadow 0.2s" }} onFocus={e => { e.target.style.borderColor = "rgba(79,195,247,0.45)"; e.target.style.boxShadow = "0 0 0 3px rgba(79,195,247,0.08)" }} onBlur={e => { e.target.style.borderColor = "rgba(255,255,255,0.08)"; e.target.style.boxShadow = "none" }} />
          <span style={{ position: "absolute", left: 16, top: "50%", transform: "translateY(-50%)", fontSize: 18, opacity: 0.4 }}>⌕</span>
        </div>

        {/* Import from role */}
        <div style={{ display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 14, flexWrap: "wrap" }}>
          <RoleImport roles={roles} allOps={allOps} onApply={applyRole} appliedRoles={appliedRoles} onRemove={removeRole} />
          <CustomRoleImport allOps={allOps} onImport={applyCustomRole} />
        </div>

        {/* Importing indicator */}
        {importing && <div style={{ padding: "10px 14px", marginBottom: 12, background: "rgba(171,71,188,0.08)", border: "1px solid rgba(171,71,188,0.2)", borderRadius: 8, fontSize: 13, color: "#ce93d8" }}>{importMsg}</div>}

        {/* Selection bar */}
        {sCount > 0 && <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 12, padding: "10px 14px", background: "rgba(255,255,255,0.03)", borderRadius: 8, border: "1px solid rgba(255,255,255,0.08)" }}>
          <div style={{ fontSize: 13, color: "#8899aa" }}><b style={{ color: "#e8ecf1" }}>{sCount}</b> action{sCount !== 1 ? "s" : ""} selected → <b style={{ color: "#e8ecf1" }}>{sOps.length}</b> unique permissions</div>
          <button onClick={clr} style={{ background: "none", border: "1px solid rgba(233,69,96,0.3)", color: "#e94560", padding: "4px 14px", borderRadius: 6, fontSize: 12, cursor: "pointer", fontFamily: "inherit" }}>Clear all</button>
        </div>}



        {/* Categories → Providers → Resource Types → Operations */}
        <div style={{ display: "flex", flexDirection: "column", gap: 6, marginBottom: 28 }}>
          {sorted.map(cat => {
            const catOpen = openCat === cat.name || isSearch;
            const catSel = hasCatSel(cat);
            const totalTypes = cat.providers.reduce((s, p) => s + p.types.length, 0);
            const singleProv = cat.providers.length === 1;
            return (
              <div key={cat.name} style={{ background: catOpen ? "rgba(255,255,255,0.03)" : catSel ? "rgba(255,255,255,0.035)" : "rgba(255,255,255,0.02)", border: `1px solid ${(catSel || catOpen) ? ac(cat.name) + "55" : "rgba(255,255,255,0.07)"}`, borderRadius: 12, overflow: "hidden", transition: "border-color 0.3s, background 0.2s, box-shadow 0.3s", boxShadow: catOpen ? `0 4px 28px rgba(0,0,0,0.3), 0 0 0 1px ${ac(cat.name)}18` : "none" }}>
                <button onClick={() => setOC(catOpen && !isSearch ? null : cat.name)} className="cat-row" style={{ width: "100%", display: "flex", alignItems: "center", gap: 12, padding: "13px 16px", background: "none", border: "none", cursor: "pointer", fontFamily: "inherit" }}>
                  <span style={{ width: 32, height: 32, borderRadius: 8, background: `${ac(cat.name)}18`, border: `1px solid ${ac(cat.name)}30`, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 15, flexShrink: 0 }}>{cat.icon}</span>
                  <span style={{ fontSize: 14, fontWeight: 600, color: ac(cat.name), flex: 1, textAlign: "left" }}>{cat.name}</span>
                  <span style={{ fontSize: 11, color: "#647a94", fontFamily: "var(--m)" }}>{totalTypes} types</span>
                  {catSel && <span style={{ width: 8, height: 8, borderRadius: 4, background: ac(cat.name), flexShrink: 0 }} />}
                  <span style={{ color: "#6b7c93", fontSize: 13, transform: catOpen ? "rotate(180deg)" : "none", transition: "transform 0.2s" }}>▾</span>
                </button>

                {catOpen && (<div style={{ padding: "0 8px 8px" }}>{cat.providers.map(prov => {
                  const pk = prov.namespace, provOpen = singleProv || openProv[pk] || isSearch, provSel = hasProvSel(prov);
                  const nsDot = prov.namespace.indexOf(".");
                  const nsPrefix = nsDot >= 0 ? prov.namespace.slice(0, nsDot + 1) : "";
                  const nsTail = nsDot >= 0 ? prov.namespace.slice(nsDot + 1) : prov.namespace;
                  return (<div key={pk} style={{ marginBottom: 2 }}>
                    {!singleProv && (<button onClick={() => setOP(s => ({ ...s, [pk]: !s[pk] }))} style={{ width: "100%", display: "flex", alignItems: "center", gap: 8, padding: "8px 10px", background: provOpen ? "rgba(255,255,255,0.02)" : "transparent", border: "none", borderRadius: 8, cursor: "pointer", fontFamily: "inherit" }}>
                      <span style={{ fontSize: 11, color: ac(cat.name), opacity: 0.6, transform: provOpen ? "rotate(90deg)" : "none", transition: "transform 0.15s" }}>▸</span>
                      <span style={{ flex: 1, textAlign: "left" }}><PathLabel prefix={nsPrefix} tail={nsTail} brightColor={provSel ? ac(cat.name) : "#aeb9c9"} size={13} highlightQuery={isSearch ? filter : ""} /></span>
                      {provSel && <span style={{ width: 6, height: 6, borderRadius: 3, background: ac(cat.name) }} />}
                      <span style={{ fontSize: 10, color: "#647a94", fontFamily: "var(--m)" }}>{prov.types.length}</span>
                    </button>)}
                    {provOpen && (() => {
                      const renderRT = (rt) => {
                        const rk = `${prov.namespace}|${rt.key}`;
                        // Search shows matched types COLLAPSED — the R/W/D/A badge marks
                        // what's inside; the user expands the one they want. No action wall.
                        const rtOpen = openRT === rk;
                        const rtSel = hasRTSel(prov, rt);
                        const sc = rtSelCount(rt);
                        const totalOps = rt.actions.reduce((s, a) => s + a.ops.length, 0);
                        const levels = groupByLevel(rt, prov.namespace);
                        const displayName = niceName(rt.name || fn(rt.key));
                        const rawType = `${prov.namespace}/${rt.key}`;
                        const presentLevels = new Set(rt.actions.map(a => a.label));
                        // While searching, work out which access levels actually contain a
                        // matching operation, so the collapsed row can mark where the hit is.
                        const matchedLevels = new Set();
                        if (isSearch) {
                          const sw = filter.toLowerCase().trim().split(/\s+/).filter(Boolean);
                          const isPathQ = filter.includes("/") || filter.toLowerCase().includes("microsoft.");
                          const nsPre = (prov.namespace + "/").toLowerCase();
                          for (const a of rt.actions) {
                            if (a.ops.some(o => { let op = o.action.toLowerCase(); if (!isPathQ && op.startsWith(nsPre)) op = op.slice(nsPre.length); return sw.every(w => op.includes(w)); })) matchedLevels.add(a.label);
                          }
                        }
                        // When a type is opened during a search, filter its actions to the query
                        // so the user lands on the match instead of scrolling the whole panel.
                        const combinedFilter = openRT === rk ? actionFilter : "";
                        const hlOps = openRT === rk ? actionFilter : "";
                        return (<div key={rt.key}>
                          <button onClick={() => { const opening = openRT !== rk; setORT(opening ? rk : null); setAF(opening && isSearch ? filter.trim() : "") }} className="rt-row" title={rawType} style={{ width: "100%", display: "flex", alignItems: "flex-start", gap: 10, padding: "10px 12px", background: rtOpen ? "rgba(255,255,255,0.04)" : "transparent", border: "none", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", transition: "background 0.15s" }}>
                            <span style={{ fontSize: 12, color: "#6b7c93", transform: rtOpen ? "rotate(90deg)" : "none", transition: "transform 0.15s", flexShrink: 0, marginTop: 3 }}>▸</span>
                            <span style={{ display: "flex", flexDirection: "column", gap: 3, minWidth: 0, textAlign: "left" }}>
                              <PathLabel prefix={prov.namespace + "/"} tail={rt.key} brightColor={rtSel ? ac(cat.name) : "#e6edf5"} size={14} highlightQuery={isSearch ? filter : ""} />
                              <span style={{ display: "flex", alignItems: "center", gap: 12 }}>
                                <span style={{ fontSize: 12, color: "#8092a8", fontFamily: "var(--m)" }}>{totalOps} action{totalOps !== 1 ? "s" : ""}</span>
                                <span style={{ display: "inline-flex", gap: 4 }} title={isSearch && matchedLevels.size ? "Match under: " + [...matchedLevels].join(", ") : "Access levels: " + [...presentLevels].join(", ")}>
                                  {["Read", "Write", "Delete", "Action"].map(lv => {
                                    const present = presentLevels.has(lv);
                                    const base = { fontSize: 12, fontWeight: 700, fontFamily: "var(--m)", borderRadius: 3, padding: "0 3px" };
                                    let style;
                                    if (!present) style = { ...base, color: "#333a4a" };
                                    else if (isSearch && matchedLevels.size) style = matchedLevels.has(lv)
                                      ? { ...base, color: LVLC[lv], background: LVLC[lv] + "33", boxShadow: `0 0 0 1px ${LVLC[lv]}66` }
                                      : { ...base, color: LVLC[lv], opacity: 0.28 };
                                    else style = { ...base, color: LVLC[lv] };
                                    return <span key={lv} style={style}>{lv[0]}</span>;
                                  })}
                                </span>
                                {sc > 0 && <span style={{ fontSize: 12, color: ac(cat.name), fontWeight: 600 }}>· {sc} selected</span>}
                              </span>
                            </span>
                          </button>

                          {/* AWS-style action panel */}
                          {rtOpen && (<div style={{ margin: "4px 0 8px", marginLeft: singleProv ? 8 : 20, padding: 16, background: "rgba(79,195,247,0.02)", border: "1px solid rgba(79,195,247,0.1)", borderRadius: 10 }}>
                            <div style={{ fontSize: 12, color: "#6b7c93", marginBottom: 8 }}>Specify actions from <b style={{ color: "#e8ecf1" }}>{displayName}</b></div>
                            {/* Action filter — always empty unless user types in it */}
                            <div style={{ position: "relative", marginBottom: 12 }}>
                              <input value={openRT === rk ? actionFilter : ""} onChange={e => { setORT(rk); setAF(e.target.value) }} onFocus={() => { if (openRT !== rk) { setORT(rk); setAF("") } }} placeholder="Filter actions..." style={{ width: "100%", boxSizing: "border-box", padding: "8px 12px 8px 32px", background: "rgba(255,255,255,0.05)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 6, color: "#e8ecf1", fontSize: 12, fontFamily: "inherit", outline: "none" }} />
                              <span style={{ position: "absolute", left: 10, top: "50%", transform: "translateY(-50%)", fontSize: 14, opacity: 0.3 }}>⌕</span>
                            </div>
                            {levels.map(([level, ops]) =>
                              <ActionGroup key={level} label={level} ops={ops} ns={prov.namespace} typeKey={rt.key} sel={sel} onToggle={toggleOps} actionFilter={combinedFilter.toLowerCase()} color={LVLC[level] || "#8899aa"} highlightQuery={hlOps} />
                            )}
                          </div>)}
                        </div>);
                      };
                      return <div style={{ paddingLeft: singleProv ? 8 : 20, display: "flex", flexDirection: "column", gap: 1 }}>
                        {prov.types.slice().sort((a, b) => (a.name || a.key).localeCompare(b.name || b.key)).map(renderRT)}
                      </div>
                    })()}
                  </div>);
                })}</div>)}
              </div>
            );
          })}
        </div>
      </div>}

      {view === "studio" && (<>
      {/* Results */}
      {sOps.length > 0 && (
        <div ref={rRef} style={{ maxWidth: 960, margin: "0 auto", padding: "0 24px 60px" }}>
          <div style={{ height: 1, background: "rgba(255,255,255,0.06)", margin: "0 0 24px" }} />
          <div style={{ marginBottom: 28 }}><h3 style={HS}>Required Permissions ({sOps.length})</h3><div style={{ display: "flex", flexDirection: "column", gap: 3 }}>{sOps.map((o, i) => <OB key={i} op={o} onRemove={removeOp} />)}</div></div>
          <div style={{ marginBottom: 28 }}><h3 style={HS}>Built-in Roles ({mRoles.length}){rolesStale && <span style={{ fontWeight: 400, fontSize: 11, color: "#6b7c93", marginLeft: 8, fontStyle: "italic" }}>updating…</span>}</h3>{!mRoles.length ? <div style={{ padding: 20, background: "rgba(233,69,96,0.08)", borderRadius: 10, border: "1px solid rgba(233,69,96,0.2)", fontSize: 13, color: "#e94560" }}>No built-in role covers 60%+ of required permissions.</div> : <div style={{ display: "flex", flexDirection: "column", gap: 10 }}>{mRoles.map((r, i) => <RoleCard key={i} role={r} total={sOps.length} open={openRole === i} toggle={() => setOR(openRole === i ? null : i)} />)}</div>}</div>
          <div style={{ background: "rgba(79,195,247,0.06)", border: "1px solid rgba(79,195,247,0.15)", borderRadius: 10, padding: 16, marginBottom: 16 }}><div style={{ fontSize: 13, color: "#8899aa", lineHeight: 1.6 }}><b style={{ color: "#4fc3f7" }}>ℹ Note:</b> Review whether the additional permissions in the built-in role are acceptable for your environment.</div></div>
          <div style={{ marginBottom: 24 }}><button onClick={() => setSJ(!showJSON)} style={{ display: "inline-flex", alignItems: "center", gap: 8, padding: "12px 24px", borderRadius: 8, cursor: "pointer", fontFamily: "inherit", background: showJSON ? "rgba(171,71,188,0.2)" : "rgba(171,71,188,0.1)", border: `1px solid rgba(171,71,188,0.5)`, color: "#ce93d8", fontSize: 14, fontWeight: 600, boxShadow: "0 4px 14px rgba(171,71,188,0.15)", transition: "all 0.2s" }}>{showJSON ? "▾" : "▸"} View Custom Role JSON</button>{showJSON && <div style={{ marginTop: 12, position: "relative" }}><pre style={{ background: "rgba(0,0,0,0.3)", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 10, padding: 16, overflowX: "auto", fontSize: 12, lineHeight: 1.6, color: "#a8c0d8", fontFamily: "var(--m)" }}>{cJSON}</pre><button onClick={() => copy(cJSON)} style={{ position: "absolute", top: 10, right: 10, padding: "6px 14px", borderRadius: 6, cursor: "pointer", background: copied ? "rgba(15,155,88,0.2)" : "rgba(255,255,255,0.08)", border: `1px solid ${copied ? "rgba(15,155,88,0.4)" : "rgba(255,255,255,0.15)"}`, color: copied ? "#0f9b58" : "#8899aa", fontSize: 12, fontFamily: "inherit" }}>{copied ? "✓ Copied" : "Copy"}</button><div style={{ marginTop: 8, fontSize: 11, color: "#647a94" }}>Deploy: <code style={{ color: "#6b7c93" }}>{dataset === "entra" ? "New-MgRoleManagementDirectoryRoleDefinition -BodyParameter (Get-Content custom-role.json | ConvertFrom-Json -AsHashtable)" : "New-AzRoleDefinition -InputFile custom-role.json"}</code></div></div>}</div>
          <div style={{ background: "rgba(255,255,255,0.02)", border: "1px solid rgba(255,255,255,0.06)", borderRadius: 10, padding: 16, marginBottom: 24 }}><div style={{ fontSize: 12, color: "#647a94", lineHeight: 1.6 }}>These are general recommendations based on {dataset === "entra" ? "Microsoft Graph" : "Azure API"} data. For individual RBAC architecture reviews, security assessments, or custom least-privilege implementations — <a href="mailto:info@simonvedder.com" style={{ color: "#6b7c93" }}>info@simonvedder.com</a> · <a href="https://simonvedder.com" style={{ color: "#6b7c93" }}>simonvedder.com</a></div></div>
        </div>
      )}
      {!sOps.length && <div style={{ textAlign: "center", padding: "30px 24px 60px", maxWidth: 960, margin: "0 auto" }}><div style={{ fontSize: 13, color: "#3a4556" }}>Select resources and actions above to see required permissions and matching built-in roles.</div></div>}
      </>)}

      {/* Sticky builder bar — always-visible summary + jump to result while browsing.
          Shown on Build and on the IaC tab so imports accumulate without a forced jump. */}
      {(view === "studio" || view === "iac") && sCount > 0 && (() => {
        const dsColor = dataset === "entra" ? "#b39dda" : "#4fc3f7";
        const best = mRoles[0];
        return <>
          <div style={{ height: 68 }} />
          <div style={{ position: "fixed", left: 0, right: 0, bottom: 0, zIndex: 60, background: "rgba(13,13,24,0.9)", backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)", borderTop: `1px solid ${dsColor}44`, boxShadow: "0 -6px 28px rgba(0,0,0,0.45)" }}>
            <div style={{ maxWidth: 960, margin: "0 auto", padding: "12px 24px", display: "flex", alignItems: "center", gap: 14, flexWrap: "wrap" }}>
              <span style={{ width: 9, height: 9, borderRadius: 5, background: dsColor, boxShadow: `0 0 10px ${dsColor}`, flexShrink: 0 }} />
              <div style={{ fontSize: 13, color: "#c8d6e5" }}>
                <b style={{ color: dsColor }}>{sCount}</b> action{sCount !== 1 ? "s" : ""} → <b style={{ color: "#e8ecf1" }}>{sOps.length}</b> permission{sOps.length !== 1 ? "s" : ""}
                {best && <span style={{ color: "#8899aa" }}> · best fit <b style={{ color: "#e8ecf1" }}>{best.name}</b> <b style={{ color: best.coverage === 1 ? "#0f9b58" : "#f5a623" }}>{Math.round(best.coverage * 100)}%</b></span>}
              </div>
              <div style={{ marginLeft: "auto", display: "flex", gap: 8 }}>
                <button onClick={clr} style={{ background: "none", border: "1px solid rgba(233,69,96,0.3)", color: "#e94560", padding: "7px 14px", borderRadius: 7, fontSize: 12.5, cursor: "pointer", fontFamily: "inherit" }}>Clear</button>
                <button onClick={() => { setView("studio"); setSJ(true); requestAnimationFrame(() => requestAnimationFrame(() => rRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }))); }} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "7px 16px", borderRadius: 7, cursor: "pointer", fontFamily: "inherit", fontSize: 12.5, fontWeight: 600, background: `${dsColor}22`, border: `1px solid ${dsColor}55`, color: dsColor }}>View role &amp; JSON ↓</button>
              </div>
            </div>
          </div>
        </>;
      })()}
      <footer style={{ padding: "24px", maxWidth: 960, margin: "0 auto", borderTop: "1px solid rgba(255,255,255,0.05)", textAlign: "center" }}><div style={{ fontSize: 12, color: "#647a94", marginBottom: 8 }}>Least Privilege Studio · Azure RBAC & Entra ID · Open Source · <a href="https://github.com/simon-vedder/least-privilege-studio" style={{ color: "#4fc3f7", textDecoration: "none" }}>GitHub</a></div><div style={{ fontSize: 12, color: "#647a94", marginBottom: 8 }}>Built by <a href="https://simonvedder.com" style={{ color: "#4fc3f7", textDecoration: "none" }}>Simon Vedder</a> · <a href="https://www.linkedin.com/in/simonvedder/" style={{ color: "#4fc3f7", textDecoration: "none" }}>LinkedIn</a></div><div style={{ fontSize: 11, color: "#3a4556", marginBottom: 8 }}>Always verify permissions in a non-production environment before deploying.</div><div style={{ fontSize: 11, color: "#3a4556" }}>No personal data collected. No cookies. <a href="https://simonvedder.com/privacy" style={{ color: "#647a94", textDecoration: "underline" }}>Privacy Policy</a> · <a href="https://simonvedder.com/terms" style={{ color: "#647a94", textDecoration: "underline" }}>Terms</a></div></footer>
    </div>
  );
}

const ROOT = { "--m": "'IBM Plex Mono',monospace", zoom: 1.08, minHeight: "100vh", background: "#07071a", backgroundImage: "radial-gradient(ellipse 70% 45% at 85% -5%, rgba(79,195,247,0.09) 0%, transparent 100%), radial-gradient(ellipse 55% 35% at -5% 20%, rgba(171,71,188,0.07) 0%, transparent 100%), linear-gradient(160deg,#07071a 0%,#0d0d24 50%,#080c14 100%)", color: "#c8d6e5", fontFamily: "'Instrument Sans',-apple-system,sans-serif" };
const HS = { fontSize: 13, fontWeight: 700, textTransform: "uppercase", letterSpacing: "0.08em", marginBottom: 14, background: "linear-gradient(90deg, #7a90a8 0%, #b0c8dc 100%)", WebkitBackgroundClip: "text", WebkitTextFillColor: "transparent", backgroundClip: "text" };

// ─── DEMO DATA ──────────────────────────────────────────────────────────────

const DR = [{ name: "Virtual Machine Contributor", id: "9980e02c", description: "Create and manage VMs. No VNet or storage access.", actions: ["Microsoft.Authorization/*/read", "Microsoft.Compute/availabilitySets/*", "Microsoft.Compute/locations/*", "Microsoft.Compute/virtualMachines/*", "Microsoft.Compute/virtualMachineScaleSets/*", "Microsoft.Compute/disks/write", "Microsoft.Compute/disks/read", "Microsoft.Compute/disks/delete", "Microsoft.Insights/alertRules/*", "Microsoft.Network/applicationGateways/backendAddressPools/join/action", "Microsoft.Network/loadBalancers/backendAddressPools/join/action", "Microsoft.Network/loadBalancers/inboundNatPools/join/action", "Microsoft.Network/loadBalancers/inboundNatRules/join/action", "Microsoft.Network/loadBalancers/probes/join/action", "Microsoft.Network/loadBalancers/read", "Microsoft.Network/locations/*", "Microsoft.Network/networkInterfaces/*", "Microsoft.Network/networkSecurityGroups/join/action", "Microsoft.Network/networkSecurityGroups/read", "Microsoft.Network/publicIPAddresses/join/action", "Microsoft.Network/publicIPAddresses/read", "Microsoft.Network/virtualNetworks/read", "Microsoft.Network/virtualNetworks/subnets/join/action", "Microsoft.ResourceHealth/availabilityStatuses/read", "Microsoft.Resources/deployments/*", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Storage/storageAccounts/listKeys/action", "Microsoft.Storage/storageAccounts/read", "Microsoft.Support/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 59 }, { name: "Contributor", id: "b24988ac", description: "Full access to manage resources. Cannot assign roles.", actions: ["*"], notActions: ["Microsoft.Authorization/*/Delete", "Microsoft.Authorization/*/Write", "Microsoft.Authorization/elevateAccess/Action"], dataActions: [], notDataActions: [], _estimatedActions: 5000 }, { name: "Reader", id: "acdd72a7", description: "View all resources.", actions: ["*/read"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 3000 }, { name: "Network Contributor", id: "4d97b98b", description: "Create and manage networks.", actions: ["Microsoft.Authorization/*/read", "Microsoft.Insights/alertRules/*", "Microsoft.Network/*", "Microsoft.ResourceHealth/availabilityStatuses/read", "Microsoft.Resources/deployments/*", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Support/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 55 }, { name: "Storage Account Contributor", id: "17d1049b", description: "Manage storage accounts. No data access.", actions: ["Microsoft.Authorization/*/read", "Microsoft.Insights/alertRules/*", "Microsoft.Insights/diagnosticSettings/*", "Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/action", "Microsoft.ResourceHealth/availabilityStatuses/read", "Microsoft.Resources/deployments/*", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Storage/storageAccounts/*", "Microsoft.Support/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 48 }, { name: "Storage Blob Data Reader", id: "2a2b9908", description: "Read blob containers and data.", actions: ["Microsoft.Storage/storageAccounts/blobServices/containers/read", "Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action"], notActions: [], dataActions: ["Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read"], notDataActions: [], _estimatedActions: 3 }, { name: "Storage Blob Data Contributor", id: "ba92f5b4", description: "Read, write, delete blob data.", actions: ["Microsoft.Storage/storageAccounts/blobServices/containers/read", "Microsoft.Storage/storageAccounts/blobServices/containers/write", "Microsoft.Storage/storageAccounts/blobServices/containers/delete", "Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action"], notActions: [], dataActions: ["Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read", "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write", "Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete"], notDataActions: [], _estimatedActions: 9 }, { name: "Key Vault Contributor", id: "f25e0fa2", description: "Manage key vaults. No data access.", actions: ["Microsoft.Authorization/*/read", "Microsoft.Insights/alertRules/*", "Microsoft.KeyVault/*", "Microsoft.Resources/deployments/*", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Support/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 48 }, { name: "Website Contributor", id: "de139f84", description: "Manage websites.", actions: ["Microsoft.Authorization/*/read", "Microsoft.Insights/alertRules/*", "Microsoft.Insights/components/*", "Microsoft.ResourceHealth/availabilityStatuses/read", "Microsoft.Resources/deployments/*", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Support/*", "Microsoft.Web/certificates/*", "Microsoft.Web/listSitesAssignedToHostName/read", "Microsoft.Web/serverFarms/join/action", "Microsoft.Web/serverFarms/read", "Microsoft.Web/sites/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 42 }, { name: "SQL DB Contributor", id: "9b7fa17d", description: "Manage SQL databases.", actions: ["Microsoft.Authorization/*/read", "Microsoft.Insights/alertRules/*", "Microsoft.ResourceHealth/availabilityStatuses/read", "Microsoft.Resources/deployments/*", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Sql/locations/*/read", "Microsoft.Sql/servers/databases/*", "Microsoft.Sql/servers/read", "Microsoft.Support/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 42 }, { name: "User Access Administrator", id: "18d7d88d", description: "Manage user access.", actions: ["*/read", "Microsoft.Authorization/*", "Microsoft.Support/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 3040 }, { name: "Desktop Virtualization Contributor", id: "082f0a83", description: "Desktop Virtualization contributor.", actions: ["Microsoft.DesktopVirtualization/*", "Microsoft.Resources/subscriptions/resourceGroups/read", "Microsoft.Resources/deployments/*", "Microsoft.Authorization/*/read", "Microsoft.Insights/alertRules/*", "Microsoft.Support/*"], notActions: [], dataActions: [], notDataActions: [], _estimatedActions: 48 }];
const _t = (p, k, a) => ({ key: k, name: k, provider: p, totalOps: a.reduce((s, x) => s + x.ops.length, 0), actions: a }); const _a = (l, o, h = false) => ({ label: l, ops: o, hasDataActions: h }); const _o = (a, t = "action") => ({ action: a, type: t });
const DC = [
  {
    name: "Compute", icon: "🖥", providers: [{
      namespace: "Microsoft.Compute", displayName: "Compute", types: [
        _t("Microsoft.Compute", "virtualMachines", [
          _a("Read", [_o("Microsoft.Compute/virtualMachines/read"), _o("Microsoft.Compute/virtualMachines/instanceView/read"), _o("Microsoft.Compute/virtualMachines/extensions/read")]),
          _a("Write", [_o("Microsoft.Compute/virtualMachines/write"), _o("Microsoft.Compute/virtualMachines/extensions/write")]),
          _a("Delete", [_o("Microsoft.Compute/virtualMachines/delete"), _o("Microsoft.Compute/virtualMachines/extensions/delete")]),
          _a("Action", [_o("Microsoft.Compute/virtualMachines/start/action"), _o("Microsoft.Compute/virtualMachines/deallocate/action"), _o("Microsoft.Compute/virtualMachines/powerOff/action"), _o("Microsoft.Compute/virtualMachines/restart/action"), _o("Microsoft.Compute/virtualMachines/runCommand/action")]),
        ]),
        _t("Microsoft.Compute", "disks", [_a("Read", [_o("Microsoft.Compute/disks/read")]), _a("Write", [_o("Microsoft.Compute/disks/write")]), _a("Delete", [_o("Microsoft.Compute/disks/delete")])]),
        _t("Microsoft.Compute", "galleries", [_a("Read", [_o("Microsoft.Compute/galleries/read"), _o("Microsoft.Compute/galleries/images/read"), _o("Microsoft.Compute/galleries/images/versions/read")]), _a("Write", [_o("Microsoft.Compute/galleries/write"), _o("Microsoft.Compute/galleries/images/write"), _o("Microsoft.Compute/galleries/images/versions/write")])]),
      ]
    }]
  },
  {
    name: "Networking", icon: "🌐", providers: [{
      namespace: "Microsoft.Network", displayName: "Network", types: [
        _t("Microsoft.Network", "virtualNetworks", [
          _a("Read", [_o("Microsoft.Network/virtualNetworks/read"), _o("Microsoft.Network/virtualNetworks/subnets/read")]),
          _a("Write", [_o("Microsoft.Network/virtualNetworks/write"), _o("Microsoft.Network/virtualNetworks/subnets/write")]),
          _a("Delete", [_o("Microsoft.Network/virtualNetworks/delete"), _o("Microsoft.Network/virtualNetworks/subnets/delete")]),
          _a("Action", [_o("Microsoft.Network/virtualNetworks/subnets/join/action")]),
        ]),
        _t("Microsoft.Network", "networkInterfaces", [_a("Read", [_o("Microsoft.Network/networkInterfaces/read")]), _a("Write", [_o("Microsoft.Network/networkInterfaces/write")]), _a("Delete", [_o("Microsoft.Network/networkInterfaces/delete")]), _a("Action", [_o("Microsoft.Network/networkInterfaces/join/action")])]),
        _t("Microsoft.Network", "publicIPAddresses", [_a("Read", [_o("Microsoft.Network/publicIPAddresses/read")]), _a("Write", [_o("Microsoft.Network/publicIPAddresses/write")]), _a("Delete", [_o("Microsoft.Network/publicIPAddresses/delete")]), _a("Action", [_o("Microsoft.Network/publicIPAddresses/join/action")])]),
        _t("Microsoft.Network", "networkSecurityGroups", [_a("Read", [_o("Microsoft.Network/networkSecurityGroups/read"), _o("Microsoft.Network/networkSecurityGroups/securityRules/read")]), _a("Write", [_o("Microsoft.Network/networkSecurityGroups/write"), _o("Microsoft.Network/networkSecurityGroups/securityRules/write")]), _a("Delete", [_o("Microsoft.Network/networkSecurityGroups/delete")]), _a("Action", [_o("Microsoft.Network/networkSecurityGroups/join/action")])]),
        _t("Microsoft.Network", "loadBalancers", [_a("Read", [_o("Microsoft.Network/loadBalancers/read")]), _a("Write", [_o("Microsoft.Network/loadBalancers/write")]), _a("Delete", [_o("Microsoft.Network/loadBalancers/delete")])]),
        _t("Microsoft.Network", "dnsZones", [_a("Read", [_o("Microsoft.Network/dnsZones/read"), _o("Microsoft.Network/dnsZones/A/read"), _o("Microsoft.Network/dnsZones/AAAA/read"), _o("Microsoft.Network/dnsZones/CNAME/read"), _o("Microsoft.Network/dnsZones/NS/read")]), _a("Write", [_o("Microsoft.Network/dnsZones/write"), _o("Microsoft.Network/dnsZones/A/write"), _o("Microsoft.Network/dnsZones/AAAA/write"), _o("Microsoft.Network/dnsZones/CNAME/write")]), _a("Delete", [_o("Microsoft.Network/dnsZones/delete")])]),
      ]
    }]
  },
  {
    name: "Storage", icon: "📦", providers: [{
      namespace: "Microsoft.Storage", displayName: "Storage", types: [
        _t("Microsoft.Storage", "storageAccounts", [
          _a("Read", [_o("Microsoft.Storage/storageAccounts/read"), _o("Microsoft.Storage/storageAccounts/blobServices/containers/read"), _o("Microsoft.Storage/storageAccounts/fileServices/fileshares/read"), _o("Microsoft.Storage/storageAccounts/tableServices/tables/read"), _o("Microsoft.Storage/storageAccounts/queueServices/queues/read")]),
          _a("Write", [_o("Microsoft.Storage/storageAccounts/write"), _o("Microsoft.Storage/storageAccounts/blobServices/containers/write"), _o("Microsoft.Storage/storageAccounts/fileServices/fileshares/write"), _o("Microsoft.Storage/storageAccounts/tableServices/tables/write")]),
          _a("Delete", [_o("Microsoft.Storage/storageAccounts/delete"), _o("Microsoft.Storage/storageAccounts/blobServices/containers/delete"), _o("Microsoft.Storage/storageAccounts/fileServices/fileshares/delete")]),
          _a("Action", [_o("Microsoft.Storage/storageAccounts/listKeys/action"), _o("Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read", "dataAction"), _o("Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write", "dataAction"), _o("Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete", "dataAction")], true),
        ]),
      ]
    }]
  },
  {
    name: "Databases", icon: "🗄", providers: [{
      namespace: "Microsoft.Sql", displayName: "SQL", types: [
        _t("Microsoft.Sql", "servers", [_a("Read", [_o("Microsoft.Sql/servers/read"), _o("Microsoft.Sql/servers/databases/read")]), _a("Write", [_o("Microsoft.Sql/servers/write"), _o("Microsoft.Sql/servers/databases/write")]), _a("Delete", [_o("Microsoft.Sql/servers/delete"), _o("Microsoft.Sql/servers/databases/delete")])]),
      ]
    }, {
      namespace: "Microsoft.DocumentDB", displayName: "Cosmos DB", types: [
        _t("Microsoft.DocumentDB", "databaseAccounts", [_a("Read", [_o("Microsoft.DocumentDB/databaseAccounts/read")]), _a("Write", [_o("Microsoft.DocumentDB/databaseAccounts/write")]), _a("Delete", [_o("Microsoft.DocumentDB/databaseAccounts/delete")])]),
      ]
    }]
  },
  {
    name: "Web + Serverless", icon: "🌍", providers: [{
      namespace: "Microsoft.Web", displayName: "App Service", types: [
        _t("Microsoft.Web", "sites", [_a("Read", [_o("Microsoft.Web/sites/read")]), _a("Write", [_o("Microsoft.Web/sites/write")]), _a("Delete", [_o("Microsoft.Web/sites/delete")])]),
        _t("Microsoft.Web", "serverfarms", [_a("Read", [_o("Microsoft.Web/serverfarms/read")]), _a("Write", [_o("Microsoft.Web/serverfarms/write")]), _a("Delete", [_o("Microsoft.Web/serverfarms/delete")])]),
      ]
    }]
  },
  {
    name: "Security", icon: "🔐", providers: [{
      namespace: "Microsoft.KeyVault", displayName: "Key Vault", types: [
        _t("Microsoft.KeyVault", "vaults", [_a("Read", [_o("Microsoft.KeyVault/vaults/read"), _o("Microsoft.KeyVault/vaults/secrets/read"), _o("Microsoft.KeyVault/vaults/keys/read")]), _a("Write", [_o("Microsoft.KeyVault/vaults/write"), _o("Microsoft.KeyVault/vaults/secrets/write"), _o("Microsoft.KeyVault/vaults/keys/write"), _o("Microsoft.KeyVault/vaults/accessPolicies/write")]), _a("Delete", [_o("Microsoft.KeyVault/vaults/delete"), _o("Microsoft.KeyVault/vaults/secrets/delete")])]),
      ]
    }]
  },
  {
    name: "Management + Governance", icon: "⚙", providers: [{
      namespace: "Microsoft.Resources", displayName: "Resource Manager", types: [
        _t("Microsoft.Resources", "subscriptions/resourceGroups", [_a("Read", [_o("Microsoft.Resources/subscriptions/resourceGroups/read")]), _a("Write", [_o("Microsoft.Resources/subscriptions/resourceGroups/write")]), _a("Delete", [_o("Microsoft.Resources/subscriptions/resourceGroups/delete")])]),
        _t("Microsoft.Resources", "deployments", [_a("Read", [_o("Microsoft.Resources/deployments/read")]), _a("Write", [_o("Microsoft.Resources/deployments/write")]), _a("Delete", [_o("Microsoft.Resources/deployments/delete")])]),
      ]
    }, {
      namespace: "Microsoft.Authorization", displayName: "Authorization", types: [
        _t("Microsoft.Authorization", "roleAssignments", [_a("Read", [_o("Microsoft.Authorization/roleAssignments/read"), _o("Microsoft.Authorization/roleDefinitions/read")]), _a("Write", [_o("Microsoft.Authorization/roleAssignments/write")]), _a("Delete", [_o("Microsoft.Authorization/roleAssignments/delete")])]),
      ]
    }]
  },
  {
    name: "Desktop Virtualization", icon: "🖵", providers: [{
      namespace: "Microsoft.DesktopVirtualization", displayName: "Virtual Desktop", types: [
        _t("Microsoft.DesktopVirtualization", "hostpools", [_a("Read", [_o("Microsoft.DesktopVirtualization/hostpools/read"), _o("Microsoft.DesktopVirtualization/hostpools/sessionhosts/read")]), _a("Write", [_o("Microsoft.DesktopVirtualization/hostpools/write"), _o("Microsoft.DesktopVirtualization/hostpools/sessionhosts/write")]), _a("Delete", [_o("Microsoft.DesktopVirtualization/hostpools/delete"), _o("Microsoft.DesktopVirtualization/hostpools/sessionhosts/delete")])]),
      ]
    }]
  },
];
