import React, { useState, useMemo, useCallback, useRef, useEffect, startTransition, useDeferredValue } from "react";

// ─── ENGINE ─────────────────────────────────────────────────────────────────
const _reCache=new Map();
function mw(p,o){if(p===o)return!0;if(p==="*")return!0;if(p==="*/read")return o.endsWith("/read");let re=_reCache.get(p);if(!re){re=new RegExp("^"+p.replace(/[.+?^${}()|[\]\\]/g,"\\$&").replace(/\\\./g,"\\.").replace(/\*/g,".*")+"$","i");_reCache.set(p,re)}return re.test(o)}
function rc(r,op){const pool=op.type==="dataAction"?(r.dataActions||[]):(r.actions||[]),not=op.type==="dataAction"?(r.notDataActions||[]):(r.notActions||[]);return pool.some(p=>mw(p,op.action))&&!not.some(p=>mw(p,op.action))}
function findRoles(roles,ops){if(!ops.length)return[];const total=ops.length,minC=Math.ceil(total*0.6);return roles.map(r=>{const ha=(r.actions||[]).some(a=>a.includes("*")),hd=(r.dataActions||[]).some(a=>a.includes("*"));if(!ha&&!hd){const maxP=(r.actions||[]).length+(r.dataActions||[]).length;if(maxP<minC)return null}let covered=0;const missed=[];for(const o of ops){if(rc(r,o))covered++;else missed.push(o)}if(covered<minC)return null;return{...r,coveredCount:covered,missedOps:missed,missedCount:missed.length,coverage:covered/total,est:r._estimatedActions||1}}).filter(Boolean).sort((a,b)=>b.coverage!==a.coverage?b.coverage-a.coverage:a.est-b.est).slice(0,10)}
function mkJSON(ops){return JSON.stringify({properties:{roleName:"Custom Least Privilege Role",description:"Generated by Least Privilege Studio for Azure",assignableScopes:["/subscriptions/<subscription-id>","/subscriptions/<subscription-id>/resourceGroups/<resource-group>","/providers/Microsoft.Management/managementGroups/<management-group-id>"],permissions:[{actions:ops.filter(o=>o.type==="action").map(o=>o.action),notActions:[],dataActions:ops.filter(o=>o.type==="dataAction").map(o=>o.action),notDataActions:[]}]}},null,2)}

// ─── SEARCH SYNONYMS ────────────────────────────────────────────────────────
const ABBREV={"vm":"virtual machines","nic":"network interfaces nics","nsg":"network security groups nsgs","vnet":"virtual networks","aks":"aks clusters managedclusters kubernetes","acr":"container registries","avd":"avd host pools virtual desktop","rg":"resource groups","lb":"load balancers","dns":"dns zones","kv":"key vaults keyvault","pip":"public ip addresses","k8s":"kubernetes aks","sql":"sql servers databases"};

// Returns { filtered: categories, isPermSearch: bool, permQuery: string }
function searchMatch(query,categories){
  if(!query.trim())return{filtered:categories,isPermSearch:false,permQuery:""};
  const q=query.toLowerCase().trim();
  // Mode 1: explicit permission path (contains / or microsoft.)
  if(q.includes("/")||q.includes("microsoft.")){
    const f=categories.map(cat=>({...cat,providers:cat.providers.map(p=>({...p,types:p.types.filter(t=>t.actions.some(a=>a.ops.some(o=>o.action.toLowerCase().includes(q))))})).filter(p=>p.types.length>0)})).filter(c=>c.providers.length>0);
    return{filtered:f,isPermSearch:true,permQuery:q};
  }
  // Mode 2: word-boundary match on names + substring match on operation paths
  const words=q.split(/\s+/).filter(Boolean);
  const f=categories.map(cat=>({...cat,providers:cat.providers.map(p=>({...p,types:p.types.filter(t=>{
    // Build name haystack
    const nameHay=(t.name+" "+t.key+" "+p.displayName+" "+cat.name).toLowerCase();
    let expandedHay=nameHay;
    for(const w of words){if(ABBREV[w])expandedHay+=" "+ABBREV[w]}
    // Check 1: ALL words match in the name context (word-boundary)
    const allMatchName=words.every(w=>{
      const wb=new RegExp("\\b"+w.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i");
      if(wb.test(expandedHay))return true;
      if(ABBREV[w])return ABBREV[w].split(/\s+/).some(sw=>new RegExp("\\b"+sw.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i").test(nameHay));
      return false;
    });
    if(allMatchName)return true;
    // Check 2: ALL words match as substrings within at least one operation path
    const allOps=t.actions.flatMap(a=>a.ops.map(o=>o.action.toLowerCase()));
    const allMatchOps=allOps.some(op=>words.every(w=>op.includes(w)));
    return allMatchOps;
  })})).filter(p=>p.types.length>0)})).filter(c=>c.providers.length>0);
  return{filtered:f,isPermSearch:false,permQuery:""};
}

// Highlight matching text in a string
function HL({text,query}){
  if(!query||query.length<2)return text;
  const words=query.toLowerCase().split(/\s+/).filter(w=>w.length>=2);
  // Also add abbreviation expansions
  const allWords=[...words];
  for(const w of words)if(ABBREV[w])allWords.push(...ABBREV[w].split(/\s+/).filter(s=>s.length>=2));
  if(!allWords.length)return text;
  const pat=allWords.map(w=>w.replace(/[.*+?^${}()|[\]\\]/g,"\\$&")).join("|");
  const re=new RegExp(`(${pat})`,"gi");
  const parts=text.split(re);
  return parts.map((p,i)=>re.test(p)?<span key={i} style={{color:"#4fc3f7",fontWeight:700}}>{p}</span>:p);
}

// ─── FRIENDLY NAMES ─────────────────────────────────────────────────────────
const FN={"virtualMachines":"Virtual Machines","virtualMachines/extensions":"VM Extensions","virtualMachineScaleSets":"VM Scale Sets","disks":"Managed Disks","snapshots":"Disk Snapshots","galleries":"Compute Galleries","galleries/images/versions":"Gallery Image Versions","availabilitySets":"Availability Sets","virtualNetworks":"Virtual Networks","virtualNetworks/subnets":"Subnets","networkInterfaces":"Network Interfaces (NICs)","publicIPAddresses":"Public IP Addresses","networkSecurityGroups":"Network Security Groups (NSGs)","loadBalancers":"Load Balancers","applicationGateways":"Application Gateways","routeTables":"Route Tables","privateDnsZones":"Private DNS Zones","privateEndpoints":"Private Endpoints","bastionHosts":"Bastion Hosts","natGateways":"NAT Gateways","azureFirewalls":"Azure Firewalls","virtualNetworkGateways":"VPN Gateways","storageAccounts":"Storage Accounts","storageAccounts/blobServices/containers":"Blob Containers","storageAccounts/blobServices/containers/blobs":"Blobs (Data Plane)","storageAccounts/fileServices/fileshares":"File Shares","storageAccounts/queueServices/queues":"Queues","storageAccounts/tableServices/tables":"Tables","servers":"Servers","servers/databases":"Databases","servers/elasticPools":"Elastic Pools","flexibleServers":"Flexible Servers","databaseAccounts":"Cosmos DB Accounts","sites":"Web Apps / Function Apps","serverfarms":"App Service Plans","staticSites":"Static Web Apps","managedClusters":"AKS Clusters","registries":"Container Registries","containerGroups":"Container Instances","vaults":"Key Vaults","vaults/secrets":"Secrets","vaults/keys":"Keys","vaults/certificates":"Certificates","hostpools":"Host Pools","hostpools/sessionhosts":"Session Hosts","applicationgroups":"Application Groups","roleAssignments":"Role Assignments","roleDefinitions":"Role Definitions","policyAssignments":"Policy Assignments","policyDefinitions":"Policy Definitions","subscriptions/resourceGroups":"Resource Groups","deployments":"Deployments","userAssignedIdentities":"Managed Identities","workspaces":"Workspaces","components":"Application Insights"};
const PN={"Microsoft.Compute":"Compute","Microsoft.Network":"Network","Microsoft.Storage":"Storage","Microsoft.ClassicStorage":"Classic Storage","Microsoft.NetApp":"NetApp Files","Microsoft.Sql":"SQL","Microsoft.DBforMySQL":"MySQL","Microsoft.DBforPostgreSQL":"PostgreSQL","Microsoft.DocumentDB":"Cosmos DB","Microsoft.Cache":"Redis Cache","Microsoft.DataFactory":"Data Factory","Microsoft.Kusto":"Data Explorer","Microsoft.Web":"App Service","Microsoft.App":"Container Apps","Microsoft.ApiManagement":"API Management","Microsoft.ContainerService":"AKS","Microsoft.ContainerRegistry":"Container Registry","Microsoft.ContainerInstance":"Container Instances","Microsoft.MachineLearningServices":"Machine Learning","Microsoft.CognitiveServices":"Cognitive Services / OpenAI","Microsoft.Search":"AI Search","Microsoft.KeyVault":"Key Vault","Microsoft.Security":"Security Center","Microsoft.SecurityInsights":"Sentinel","Microsoft.ManagedIdentity":"Managed Identity","Microsoft.Insights":"Monitor / Insights","Microsoft.OperationalInsights":"Log Analytics","Microsoft.Authorization":"Authorization","Microsoft.Resources":"Resource Manager","Microsoft.CostManagement":"Cost Management","Microsoft.Support":"Support","Microsoft.Logic":"Logic Apps","Microsoft.EventHub":"Event Hubs","Microsoft.EventGrid":"Event Grid","Microsoft.ServiceBus":"Service Bus","Microsoft.Devices":"IoT Hub","Microsoft.Databricks":"Databricks","Microsoft.Synapse":"Synapse Analytics","Microsoft.DesktopVirtualization":"Virtual Desktop","Microsoft.RecoveryServices":"Recovery Services","Microsoft.DevTestLab":"DevTest Labs","Microsoft.Migrate":"Migrate"};
function fn(k){return FN[k]||k.split("/").pop().replace(/([a-z])([A-Z])/g,"$1 $2").replace(/([A-Z]+)([A-Z][a-z])/g,"$1 $2").replace(/^./,s=>s.toUpperCase()).trim()}
function pn(ns){return PN[ns]||ns.replace("Microsoft.","")}

// Classify an operation into access level
function accessLevel(opAction){
  const last=opAction.split("/").pop().toLowerCase();
  const prev=opAction.split("/").slice(-2,-1)[0]?.toLowerCase()||"";
  if(last==="read")return"Read";
  if(last==="write")return"Write";
  if(last==="delete")return"Delete";
  if(last==="action"){
    if(["join","start","stop","deallocate","poweroff","restart","reboot","listkeys","regeneratekey","failover","backup","restore"].includes(prev))return"Action";
    return"Action";
  }
  return"Action";
}

// Short display name for an operation (just the meaningful part)
function opShortName(action, ns){
  const rest=action.slice(ns.length+1);
  return rest;
}

// ─── DATA ───────────────────────────────────────────────────────────────────
function useData(){const[c,sC]=useState([]);const[r,sR]=useState([]);const[h,sH]=useState([]);const[m,sM]=useState(null);const[l,sL]=useState(true);const[d,sD]=useState(false);
useEffect(()=>{(async()=>{
  // Use relative path so it works with any base path
  const base=(import.meta.env.BASE_URL||"/least-privilege-studio/").replace(/\/?$/,"/");
  const f=p=>fetch(`${base}data/${p}`).then(x=>x.ok?x.json():null);
  try{const[a,b,c2,d2]=await Promise.allSettled([f("ui-structure.json"),f("roles.json"),f("dependency-hints.json"),f("metadata.json")]);
  const cv=a.status==="fulfilled"&&a.value,rv=b.status==="fulfilled"&&b.value;
  if(cv?.length&&rv?.length){sC(cv);sR(rv);sH(c2.status==="fulfilled"&&c2.value||DH);sM(d2.status==="fulfilled"&&d2.value||null)}
  else{sD(true);sC(DC);sR(DR);sH(DH)}}catch{sD(true);sC(DC);sR(DR);sH(DH)}sL(false)})()},[]);
return{categories:c,roles:r,hints:h,meta:m,loading:l,isDemo:d}}

// ─── STYLES ─────────────────────────────────────────────────────────────────
const AC={"Compute":"#e94560","Networking":"#4fc3f7","Storage":"#0f9b58","Databases":"#5c6bc0","Web + Serverless":"#ef5350","Containers":"#29b6f6","AI + Machine Learning":"#ce93d8","Security":"#f5a623","Identity":"#ff7043","DevOps":"#8d6e63","Monitor":"#fdd835","Management + Governance":"#78909c","Integration":"#26a69a","Analytics":"#ab47bc","Desktop Virtualization":"#7e57c2","Internet of Things":"#00acc1","Backup + Recovery":"#66bb6a","Migration":"#a1887f","Other":"#90a4ae"};
const ac=c=>AC[c]||"#4fc3f7";
const LVLC={"Read":"#4fc3f7","Write":"#f5a623","Delete":"#e94560","Action":"#ab47bc"};

// ─── COMPONENTS ─────────────────────────────────────────────────────────────
function Meter({v}){const p=Math.round(v*100),c=p===100?"#0f9b58":p>=80?"#f5a623":"#e94560";return<div style={{display:"flex",alignItems:"center",gap:10}}><div style={{flex:1,height:6,background:"#2a2a4a",borderRadius:3,overflow:"hidden"}}><div style={{width:`${p}%`,height:"100%",background:c,borderRadius:3,transition:"width 0.4s"}}/></div><span style={{fontFamily:"var(--m)",fontSize:13,color:c,minWidth:44,textAlign:"right"}}>{p}%</span></div>}
function OB({op,onRemove}){const d=op.type==="dataAction";return<div style={{display:"flex",alignItems:"center",gap:8,padding:"5px 10px",background:d?"rgba(245,166,35,0.08)":"rgba(79,195,247,0.08)",border:`1px solid ${d?"rgba(245,166,35,0.2)":"rgba(79,195,247,0.15)"}`,borderRadius:6,fontFamily:"var(--m)",fontSize:11.5,color:"#c8d6e5"}}><span style={{fontSize:9,fontWeight:700,padding:"2px 6px",borderRadius:3,textTransform:"uppercase",letterSpacing:"0.05em",background:d?"rgba(245,166,35,0.2)":"rgba(79,195,247,0.15)",color:d?"#f5a623":"#4fc3f7"}}>{d?"Data":"Action"}</span><span style={{wordBreak:"break-all",flex:1}}>{op.action}</span>{onRemove&&<button onClick={()=>onRemove(op.action)} style={{background:"none",border:"none",color:"#6b7c93",cursor:"pointer",fontSize:16,padding:"0 2px",lineHeight:1,flexShrink:0,opacity:0.6}} title="Remove this permission">×</button>}</div>}
function RoleCard({role,total,open,toggle}){const cc=role.coverage===1?"#0f9b58":role.coverage>=0.8?"#f5a623":"#e94560";return<div onClick={toggle} style={{background:"rgba(255,255,255,0.03)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:10,padding:16,cursor:"pointer",borderLeft:`3px solid ${cc}`,transition:"all 0.2s"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start",marginBottom:6}}><div style={{flex:1}}><div style={{fontSize:15,fontWeight:600,color:"#e8ecf1",marginBottom:2}}>{role.name}</div><div style={{fontSize:11,color:"#4a5568",fontFamily:"var(--m)",marginBottom:3}}>{role.id}</div><div style={{fontSize:12,color:"#6b7c93",lineHeight:1.4}}>{role.description}</div></div><span style={{fontSize:16,color:"#6b7c93",marginLeft:12,transform:open?"rotate(180deg)":"none",transition:"transform 0.2s"}}>▾</span></div><div style={{display:"flex",gap:14,marginTop:8,flexWrap:"wrap",fontSize:12}}><span style={{color:"#8899aa"}}>Coverage: <span style={{color:cc,fontWeight:700}}>{role.coveredCount}/{total}</span></span>{role.missedCount>0&&<span style={{color:"#e94560"}}>Missing: {role.missedCount}</span>}<span style={{color:"#6b7c93"}}>~{role.est} total actions</span></div><div style={{marginTop:8}}><Meter v={role.coverage}/></div>{open&&<div style={{marginTop:14,paddingTop:14,borderTop:"1px solid rgba(255,255,255,0.06)"}}>{role.missedCount>0&&<div style={{marginBottom:12}}><div style={{fontSize:12,fontWeight:600,color:"#e94560",marginBottom:8}}>⚠ Not covered:</div><div style={{display:"flex",flexDirection:"column",gap:4}}>{role.missedOps.map((o,i)=><OB key={i} op={o}/>)}</div></div>}<div style={{fontSize:12,color:"#6b7c93",lineHeight:1.6}}>This role grants ~<b style={{color:"#c8d6e5"}}>{role.est}</b> actions. You selected <b style={{color:"#c8d6e5"}}>{total}</b>. Review whether the extra actions are acceptable.</div></div>}</div>}
function HintBar({hints,onAdd,sel}){const[expanded,setExp]=useState(false);const u=hints.filter(h=>!sel.has(h.opKey));if(!u.length)return null;const LIMIT=10,hasMore=u.length>LIMIT,visible=expanded?u:u.slice(0,LIMIT);return<div style={{margin:"12px 0",padding:14,background:"rgba(245,166,35,0.06)",border:"1px solid rgba(245,166,35,0.18)",borderRadius:10}}><div style={{fontSize:12,fontWeight:600,color:"#f5a623",marginBottom:8}}>💡 Typically also requires ({u.length}):</div><div style={{display:"flex",flexDirection:"column",gap:6}}>{visible.map((h,i)=><div key={i} style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:8}}><span style={{fontFamily:"var(--m)",fontSize:11,color:"#c8d6e5",wordBreak:"break-all"}}>{h.action} <span style={{color:"#6b7c93"}}>({h.reason})</span></span><button onClick={()=>onAdd(h)} style={{padding:"3px 10px",borderRadius:5,fontSize:11,fontWeight:600,cursor:"pointer",background:"rgba(245,166,35,0.15)",border:"1px solid rgba(245,166,35,0.3)",color:"#f5a623",fontFamily:"inherit",whiteSpace:"nowrap",flexShrink:0}}>+ Add</button></div>)}</div>{hasMore&&<button onClick={()=>setExp(!expanded)} style={{marginTop:8,padding:"5px 12px",borderRadius:5,fontSize:11,fontWeight:500,cursor:"pointer",background:"none",border:"1px solid rgba(245,166,35,0.2)",color:"#f5a623",fontFamily:"inherit",width:"100%"}}>{expanded?"▲ Show less":`▼ Show all ${u.length} recommendations`}</button>}</div>}

// AWS-style Action Group (Read, Write, Delete, Action)
const ActionGroup=React.memo(function ActionGroup({label,ops,ns,sel,onToggle,actionFilter,color,highlightQuery}){
  const[userClosed,setUC]=useState(false);
  const[userOpened,setUO]=useState(false);
  const selCount=ops.filter(op=>sel[op.action]).length;
  const afWords=actionFilter?actionFilter.split(/\s+/).filter(Boolean):[];
  const filtered=afWords.length?ops.filter(op=>{const p=opShortName(op.action,ns).toLowerCase();return afWords.every(w=>p.includes(w))}):ops;
  // Default open if filter is active, but respect user toggle
  const isOpen=userClosed?false:userOpened?true:(afWords.length>0);
  if(afWords.length>0&&!filtered.length)return null;
  
  const toggle=()=>{if(isOpen){setUC(true);setUO(false)}else{setUO(true);setUC(false)}};

  return<div style={{marginBottom:4}}>
    <button onClick={toggle} style={{display:"flex",alignItems:"center",gap:8,padding:"6px 0",background:"none",border:"none",cursor:"pointer",fontFamily:"inherit",width:"100%"}}>
      <span style={{fontSize:11,color:"#6b7c93",transform:isOpen?"rotate(90deg)":"none",transition:"transform 0.15s"}}>▸</span>
      <span style={{fontSize:13,fontWeight:600,color}}>{label}</span>
      <span style={{fontSize:12,color:"#6b7c93"}}>({selCount>0?<span style={{color}}>selected {selCount}/</span>:""}{afWords.length?filtered.length:ops.length})</span>
    </button>
    {isOpen&&<div style={{paddingLeft:20,display:"flex",flexDirection:"column",gap:2,marginBottom:8}}>
      <label style={{display:"flex",alignItems:"center",gap:8,padding:"4px 0",cursor:"pointer",fontSize:12,color:"#8899aa"}}>
        <input type="checkbox" checked={selCount===ops.length&&ops.length>0} onChange={()=>{
          const allOn=selCount===ops.length;const u={};for(const op of ops)u[op.action]=!allOn;onToggle(u);
        }} style={{accentColor:color}}/>
        All {label.toLowerCase()} actions
      </label>
      {filtered.map(op=>(
        <label key={op.action} style={{display:"flex",alignItems:"center",gap:8,padding:"3px 0",cursor:"pointer"}}>
          <input type="checkbox" checked={!!sel[op.action]} onChange={()=>onToggle({[op.action]:!sel[op.action]})} style={{accentColor:color}}/>
          <span style={{fontFamily:"var(--m)",fontSize:11.5,color:sel[op.action]?"#e8ecf1":"#8899aa",wordBreak:"break-all"}}>{highlightQuery?<HL text={opShortName(op.action,ns)} query={highlightQuery}/>:opShortName(op.action,ns)}</span>
          {op.type==="dataAction"&&<span style={{fontSize:9,padding:"1px 5px",borderRadius:3,background:"rgba(245,166,35,0.15)",color:"#f5a623",fontWeight:600}}>Data</span>}
        </label>
      ))}
    </div>}
  </div>;
});

// ─── ROLE PICKER ────────────────────────────────────────────────────────────
// Fast role resolution: pre-build an index of all operations, then match
function useOpIndex(categories) {
  return useMemo(() => {
    const actions = []; // {action, type}
    const actionSet = new Set();
    for (const cat of categories) for (const p of cat.providers) for (const t of p.types) for (const a of t.actions) for (const op of a.ops) {
      if (!actionSet.has(op.action)) { actionSet.add(op.action); actions.push(op); }
    }
    return actions;
  }, [categories]);
}

function resolveRoleFast(role, allOps) {
  const matched = new Set();
  // Pre-check simple wildcards first (fast path)
  const hasWildAll = role.actions.includes("*");
  const hasWildRead = role.actions.includes("*/read");
  
  for (const op of allOps) {
    const pool = op.type === "dataAction" ? (role.dataActions || []) : (role.actions || []);
    const not = op.type === "dataAction" ? (role.notDataActions || []) : (role.notActions || []);
    
    // Fast path for common wildcards
    let match = false;
    if (op.type !== "dataAction") {
      if (hasWildAll) match = true;
      else if (hasWildRead && op.action.endsWith("/read")) match = true;
    }
    if (!match) match = pool.some(p => mw(p, op.action));
    if (!match) continue;
    if (not.some(p => mw(p, op.action))) continue;
    matched.add(op.action);
  }
  return matched;
}

function RoleImport({ roles, allOps, onApply, appliedRoles, onRemove }) {
  const [open, setOpen] = useState(false);
  const [query, setQ] = useState("");
  const ref = useRef(null);

  useEffect(() => {
    const h = e => { if (ref.current && !ref.current.contains(e.target)) setOpen(false) };
    document.addEventListener("mousedown", h);
    return () => document.removeEventListener("mousedown", h);
  }, []);

  const filtered = useMemo(() => {
    if (!query.trim()) return []; // Show nothing until user types
    const q = query.toLowerCase();
    return roles.filter(r => r.name.toLowerCase().includes(q) || r.description.toLowerCase().includes(q));
  }, [roles, query]);

  return (
    <div style={{ display: "flex", alignItems: "flex-start", gap: 8, marginBottom: 14, flexWrap: "wrap" }}>
      {/* Applied role tags */}
      {appliedRoles.map(r => (
        <span key={r.id} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "5px 10px", borderRadius: 6, fontSize: 12, fontWeight: 500, background: "rgba(79,195,247,0.1)", border: "1px solid rgba(79,195,247,0.25)", color: "#4fc3f7" }}>
          {r.name}
          <button onClick={() => onRemove(r)} style={{ background: "none", border: "none", color: "#4fc3f7", cursor: "pointer", fontSize: 14, padding: 0, lineHeight: 1, opacity: 0.7 }}>×</button>
        </span>
      ))}

      {/* Import button + dropdown */}
      <div ref={ref} style={{ position: "relative" }}>
        <button onClick={() => setOpen(!open)} style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "5px 12px", borderRadius: 6, fontSize: 12, fontWeight: 500, cursor: "pointer", fontFamily: "inherit", background: open ? "rgba(171,71,188,0.12)" : "rgba(255,255,255,0.04)", border: `1px solid ${open ? "rgba(171,71,188,0.3)" : "rgba(255,255,255,0.1)"}`, color: open ? "#ce93d8" : "#6b7c93" }}>
          <span style={{ fontSize: 13 }}>+</span> Import from role
        </button>

        {open && (
          <div style={{ position: "absolute", top: "100%", left: 0, zIndex: 50, marginTop: 6, width: 380, background: "#1a1a2e", border: "1px solid rgba(255,255,255,0.12)", borderRadius: 10, boxShadow: "0 8px 32px rgba(0,0,0,0.5)", overflow: "hidden" }}>
            <div style={{ padding: "10px 12px 8px", borderBottom: "1px solid rgba(255,255,255,0.06)" }}>
              <input
                value={query} autoFocus
                onChange={e => setQ(e.target.value)}
                placeholder="Type to search roles..."
                style={{ width: "100%", boxSizing: "border-box", padding: "8px 12px", background: "rgba(255,255,255,0.06)", border: "1px solid rgba(255,255,255,0.1)", borderRadius: 6, color: "#e8ecf1", fontSize: 12.5, fontFamily: "inherit", outline: "none" }}
                onKeyDown={e => { if (e.key === "Escape") { setOpen(false); setQ("") } }}
              />
            </div>
            <div style={{ maxHeight: 300, overflowY: "auto" }}>
              {!query.trim() && <div style={{ padding: "16px 14px", fontSize: 12, color: "#4a5568", textAlign: "center" }}>Start typing to search {roles.length} built-in roles</div>}
              {filtered.map(r => {
                const already = appliedRoles.some(a => a.id === r.id);
                return (
                  <button key={r.id}
                    onClick={() => { if (!already) { onApply(r); setQ(""); setOpen(false) } }}
                    style={{ width: "100%", display: "flex", flexDirection: "column", gap: 2, padding: "9px 14px", background: already ? "rgba(79,195,247,0.06)" : "transparent", border: "none", borderBottom: "1px solid rgba(255,255,255,0.03)", cursor: already ? "default" : "pointer", fontFamily: "inherit", textAlign: "left", opacity: already ? 0.5 : 1 }}
                    onMouseEnter={e => { if (!already) e.currentTarget.style.background = "rgba(255,255,255,0.05)" }}
                    onMouseLeave={e => { e.currentTarget.style.background = already ? "rgba(79,195,247,0.06)" : "transparent" }}
                  >
                    <div style={{ fontSize: 13, fontWeight: 500, color: already ? "#6b7c93" : "#e8ecf1" }}>{r.name}{already && " ✓"}</div>
                    <div style={{ fontSize: 11, color: "#4a5568", lineHeight: 1.3 }}>{r.description}</div>
                  </button>
                );
              })}
              {query.trim() && !filtered.length && <div style={{ padding: "16px 14px", fontSize: 12, color: "#4a5568", textAlign: "center" }}>No roles found</div>}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function CustomRoleImport({allOps,onImport}){
  const[open,setOpen]=useState(false);
  const[json,setJson]=useState("");
  const[error,setErr]=useState("");
  const ref=useRef(null);
  useEffect(()=>{const h=e=>{if(ref.current&&!ref.current.contains(e.target))setOpen(false)};document.addEventListener("mousedown",h);return()=>document.removeEventListener("mousedown",h)},[]);
  
  const doImport=()=>{
    try{
      const parsed=JSON.parse(json);
      // Support both formats: {properties:{permissions:[{actions}]}} and {Actions:[]}
      let actions=[],dataActions=[];
      if(parsed.properties?.permissions?.[0]){
        actions=parsed.properties.permissions[0].actions||[];
        dataActions=parsed.properties.permissions[0].dataActions||[];
      }else{
        actions=parsed.Actions||parsed.actions||[];
        dataActions=parsed.DataActions||parsed.dataActions||[];
      }
      if(!actions.length&&!dataActions.length){setErr("No actions found in JSON");return}
      const role={name:parsed.properties?.roleName||parsed.Name||"Custom Role",actions,notActions:parsed.properties?.permissions?.[0]?.notActions||parsed.NotActions||[],dataActions,notDataActions:parsed.properties?.permissions?.[0]?.notDataActions||parsed.NotDataActions||[]};
      onImport(role);
      setOpen(false);setJson("");setErr("");
    }catch(e){setErr("Invalid JSON: "+e.message)}
  };
  
  return<div ref={ref} style={{position:"relative"}}>
    <button onClick={()=>setOpen(!open)} style={{display:"inline-flex",alignItems:"center",gap:6,padding:"5px 12px",borderRadius:6,fontSize:12,fontWeight:500,cursor:"pointer",fontFamily:"inherit",background:open?"rgba(79,195,247,0.12)":"rgba(255,255,255,0.04)",border:`1px solid ${open?"rgba(79,195,247,0.3)":"rgba(255,255,255,0.1)"}`,color:open?"#4fc3f7":"#6b7c93"}}>
      <span style={{fontSize:13}}>+</span> Import custom JSON
    </button>
    {open&&<div style={{position:"absolute",top:"100%",left:0,zIndex:50,marginTop:6,width:400,background:"#1a1a2e",border:"1px solid rgba(255,255,255,0.12)",borderRadius:10,boxShadow:"0 8px 32px rgba(0,0,0,0.5)",padding:14}}>
      <div style={{fontSize:12,color:"#8899aa",marginBottom:8}}>Paste a custom role JSON definition</div>
      <textarea value={json} onChange={e=>{setJson(e.target.value);setErr("")}} placeholder='{"properties":{"permissions":[{"actions":["Microsoft.Compute/virtualMachines/read"]}]}}' style={{width:"100%",boxSizing:"border-box",height:120,padding:10,background:"rgba(255,255,255,0.05)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:6,color:"#e8ecf1",fontSize:11,fontFamily:"var(--m)",outline:"none",resize:"vertical"}}/>
      {error&&<div style={{fontSize:11,color:"#e94560",marginTop:6}}>{error}</div>}
      <button onClick={doImport} style={{marginTop:8,padding:"6px 16px",borderRadius:6,fontSize:12,fontWeight:600,cursor:"pointer",background:"rgba(79,195,247,0.15)",border:"1px solid rgba(79,195,247,0.3)",color:"#4fc3f7",fontFamily:"inherit"}}>Import</button>
    </div>}
  </div>;
}
export default function App(){
  const{categories,roles,hints,meta,loading,isDemo}=useData();
  const allOps=useOpIndex(categories);
  // sel: { "Microsoft.Compute/virtualMachines/read": true }
  const[sel,setSel]=useState({});
  const[appliedRoles,setAR]=useState([]);
  const[openCat,setOC]=useState(null);
  const[openProv,setOP]=useState({});
  const[openRT,setORT]=useState(null); // only one RT open at a time (like AWS)
  const[openRole,setOR]=useState(null);
  const[showJSON,setSJ]=useState(false);
  const[copied,setCP]=useState(false);
  const[filterInput,setFI]=useState("");
  const[filter,setF]=useState("");
  const[actionFilter,setAF]=useState("");
  const rRef=useRef(null);
  const debounceRef=useRef(null);
  const handleSearch=useCallback(v=>{
    setFI(v);
    if(debounceRef.current)clearTimeout(debounceRef.current);
    // Immediate for 0 length (clearing) or 3+ chars, debounce for 1-2 chars
    if(!v.trim()||v.trim().length>=3){setF(v)}
    else{debounceRef.current=setTimeout(()=>setF(v),400)}
  },[]);

  const toggleOps=useCallback((updates)=>{
    startTransition(()=>{
      setSel(prev=>{
        const next={...prev};
        for(const[action,val]of Object.entries(updates)){
          if(val)next[action]=true;
          else delete next[action];
        }
        return next;
      });
    });
  },[]);

  // Apply a built-in role: resolve its wildcards and select all matching operations
  const[importing,setImporting]=useState(false);
  const[importMsg,setImportMsg]=useState("");
  const applyRole=useCallback((role)=>{
    const isBroad=role.actions.includes("*")||role.actions.includes("*/read");
    setImporting(true);
    setImportMsg(isBroad?"Importing broad role — this may take a moment...":"Importing role permissions...");
    setAR(prev=>[...prev,role]);
    // Process in next frame to show loading state
    requestAnimationFrame(()=>{
      const ops=resolveRoleFast(role,allOps);
      const newSel={};
      for(const a of ops)newSel[a]=true;
      startTransition(()=>{setSel(prev=>({...prev,...newSel}))});
      setImporting(false);
      setImportMsg("");
    });
  },[allOps]);

  const removeRole=useCallback((role)=>{
    setAR(prev=>prev.filter(r=>r.id!==role.id));
  },[]);
  const applyCustomRole=useCallback((role)=>{
    const ops=resolveRoleFast(role,allOps);
    startTransition(()=>{setSel(prev=>{const n={...prev};for(const a of ops)n[a]=true;return n})});
    setAR(prev=>[...prev,{...role,id:"custom-"+Date.now()}]);
  },[allOps]);

  // Collect selected operations with their type info
  // Fast: use pre-built index instead of scanning all categories
  const sOps=useMemo(()=>allOps.filter(op=>sel[op.action]),[sel,allOps]);

  const sCount=Object.keys(sel).length;

  // Dependency hints mapped to individual operations
  const aHints=useMemo(()=>{
    const all=[];
    for(const h of hints){
      // Check if any trigger operation is selected
      const triggerSelected=categories.some(cat=>cat.providers.some(prov=>prov.types.some(t=>{
        if(t.key!==h.trigger.resourceType||prov.namespace!==h.trigger.provider)return false;
        return t.actions.some(a=>a.label===h.trigger.actionGroup&&a.ops.some(op=>sel[op.action]));
      })));
      if(!triggerSelected)continue;
      for(const hint of h.hints){
        // Find the actual operations for this hint
        for(const cat of categories)for(const prov of cat.providers){
          if(prov.namespace!==hint.provider)continue;
          for(const t of prov.types){
            if(t.key!==hint.resourceType)continue;
            for(const a of t.actions){
              if(a.label!==hint.actionGroup)continue;
              for(const op of a.ops){
                if(!sel[op.action])all.push({...op,reason:hint.reason,opKey:op.action});
              }
            }
          }
        }
      }
    }
    const seen=new Set(),unique=[];
    for(const h of all)if(!seen.has(h.opKey)){seen.add(h.opKey);unique.push(h)}
    return unique;
  },[sel,hints,categories]);

  const selKeySet=useMemo(()=>new Set(Object.keys(sel)),[sel]);
  const addHint=useCallback(h=>{setSel(prev=>({...prev,[h.action]:true}))},[]);
  // Defer heavy role matching so UI stays responsive
  const deferredOps=useDeferredValue(sOps);
  const rolesStale=deferredOps!==sOps;
  const mRoles=useMemo(()=>findRoles(roles,deferredOps),[roles,deferredOps]);
  const cJSON=useMemo(()=>mkJSON(sOps),[sOps]);
  const clr=useCallback(()=>{setSel({});setOR(null);setSJ(false);setAR([]);setFI("");setF("")},[]);
  const copy=useCallback(txt=>{navigator.clipboard.writeText(txt);setCP(true);setTimeout(()=>setCP(false),2000)},[]);
  const removeOp=useCallback(action=>{startTransition(()=>{setSel(prev=>{const n={...prev};delete n[action];return n})})},[]);

  // Search
  const isSearch=filter.trim().length>0;
  const{filtered:searchFiltered,isPermSearch,permQuery}=useMemo(()=>searchMatch(filter,categories),[filter,categories]);
  const sorted=useMemo(()=>searchFiltered.map(cat=>({...cat,providers:cat.providers.map(p=>({...p,types:[...p.types]}))})),[searchFiltered]);

  // When searching, compute which resource types matched via operation paths (not just name)
  // These should auto-expand with the search term as action filter
  const searchHasOpMatch=useMemo(()=>{
    if(!isSearch)return new Set();
    const q=filter.toLowerCase().trim();
    const words=q.split(/\s+/).filter(Boolean);
    const matched=new Set();
    for(const cat of searchFiltered)for(const p of cat.providers)for(const t of p.types){
      // ALL words must match within at least one operation path
      const hasOpMatch=t.actions.some(a=>a.ops.some(o=>{
        const op=o.action.toLowerCase();
        return words.every(w=>op.includes(w));
      }));
      if(hasOpMatch)matched.add(`${p.namespace}|${t.key}`);
    }
    return matched;
  },[isSearch,filter,searchFiltered]);

  // The global action filter: when searching, pass the search query to filter operations inside panels
  const globalActionFilter=useMemo(()=>{
    if(!isSearch)return"";
    return filter.toLowerCase().trim();
  },[isSearch,filter]);

  // No auto-scroll — user scrolls to results manually

  // Group a resource type's operations by access level
  function groupByLevel(rt,ns){
    const groups={Read:[],Write:[],Delete:[],Action:[]};
    for(const a of rt.actions)for(const op of a.ops){
      const lvl=accessLevel(op.action);
      groups[lvl].push(op);
    }
    return Object.entries(groups).filter(([,ops])=>ops.length>0);
  }

  function hasCatSel(cat){return cat.providers.some(p=>p.types.some(t=>t.actions.some(a=>a.ops.some(op=>sel[op.action]))))}
  function hasProvSel(p){return p.types.some(t=>t.actions.some(a=>a.ops.some(op=>sel[op.action])))}
  function hasRTSel(p,t){return t.actions.some(a=>a.ops.some(op=>sel[op.action]))}
  function rtSelCount(t){let c=0;for(const a of t.actions)for(const op of a.ops)if(sel[op.action])c++;return c}

  if(loading)return<div style={{...ROOT,display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{color:"#6b7c93"}}>Loading...</div></div>;

  return(
    <div style={ROOT}>
      <style>{`*{box-sizing:border-box}html,body,#root{margin:0;padding:0}`}</style>
      <link href="https://fonts.googleapis.com/css2?family=Instrument+Sans:wght@400;500;600;700&family=IBM+Plex+Mono:wght@400;500;600&display=swap" rel="stylesheet"/>
      <header style={{padding:"40px 24px 16px",maxWidth:960,margin:"0 auto"}}>
        <div style={{display:"flex",alignItems:"center",gap:12,marginBottom:4}}>
          <img src={`${import.meta.env.BASE_URL}icon.png`} alt="" style={{width:38,height:38,borderRadius:10}}/>
          <h1 style={{fontSize:22,fontWeight:700,color:"#e8ecf1",margin:0}}>Least Privilege Studio for Azure</h1>
        </div>
        <p style={{fontSize:13,color:"#6b7c93",margin:"0 0 4px",fontWeight:500}}>Developer tool for Azure RBAC permissions</p>
        <p style={{fontSize:13,color:"#4a5568",margin:0,lineHeight:1.5,maxWidth:640}}>Select resources and actions you need. Get least-privilege built-in roles and custom role definitions.</p>
        {isDemo&&<div style={{marginTop:10,padding:"8px 14px",borderRadius:8,fontSize:12,background:"rgba(245,166,35,0.1)",border:"1px solid rgba(245,166,35,0.2)",color:"#f5a623"}}>⚠ Demo data. Run <code style={{background:"rgba(0,0,0,0.2)",padding:"1px 5px",borderRadius:3}}>npm run sync:all</code> to load all Azure RBAC data.</div>}
        {meta&&<div style={{marginTop:6,fontSize:11,color:"#3a4556"}}>{meta.roleCount} roles · {meta.operationCount} operations · {meta.categoryCount} categories · Synced: {new Date(meta.lastSync).toLocaleDateString()}</div>}
      </header>

      <div style={{maxWidth:960,margin:"0 auto",padding:"0 24px"}}>
        {/* Search */}
        <div style={{position:"relative",marginBottom:12}}>
          <input value={filterInput} onChange={e=>handleSearch(e.target.value)} placeholder="Search resources... e.g. virtual machine, blob, aks, /start" style={{width:"100%",boxSizing:"border-box",padding:"12px 16px 12px 44px",background:"rgba(255,255,255,0.05)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:10,color:"#e8ecf1",fontSize:14,fontFamily:"inherit",outline:"none"}} onFocus={e=>{e.target.style.borderColor="rgba(79,195,247,0.4)"}} onBlur={e=>{e.target.style.borderColor="rgba(255,255,255,0.1)"}}/>
          <span style={{position:"absolute",left:16,top:"50%",transform:"translateY(-50%)",fontSize:18,opacity:0.4}}>⌕</span>
        </div>

        {/* Import from role */}
        <div style={{display:"flex",alignItems:"flex-start",gap:8,marginBottom:14,flexWrap:"wrap"}}>
          <RoleImport roles={roles} allOps={allOps} onApply={applyRole} appliedRoles={appliedRoles} onRemove={removeRole}/>
          <CustomRoleImport allOps={allOps} onImport={applyCustomRole}/>
        </div>

        {/* Importing indicator */}
        {importing&&<div style={{padding:"10px 14px",marginBottom:12,background:"rgba(171,71,188,0.08)",border:"1px solid rgba(171,71,188,0.2)",borderRadius:8,fontSize:13,color:"#ce93d8"}}>{importMsg}</div>}

        {/* Selection bar */}
        {sCount>0&&<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:12,padding:"10px 14px",background:"rgba(255,255,255,0.03)",borderRadius:8,border:"1px solid rgba(255,255,255,0.08)"}}>
          <div style={{fontSize:13,color:"#8899aa"}}><b style={{color:"#e8ecf1"}}>{sCount}</b> action{sCount!==1?"s":""} selected → <b style={{color:"#e8ecf1"}}>{sOps.length}</b> unique permissions</div>
          <button onClick={clr} style={{background:"none",border:"1px solid rgba(233,69,96,0.3)",color:"#e94560",padding:"4px 14px",borderRadius:6,fontSize:12,cursor:"pointer",fontFamily:"inherit"}}>Clear all</button>
        </div>}

        {aHints.length>0&&<HintBar hints={aHints} onAdd={addHint} sel={selKeySet}/>}

        {/* Categories → Providers → Resource Types → Operations */}
        <div style={{display:"flex",flexDirection:"column",gap:6,marginBottom:28}}>
          {sorted.map(cat=>{
            const catOpen=openCat===cat.name||isSearch;
            const catSel=hasCatSel(cat);
            const totalTypes=cat.providers.reduce((s,p)=>s+p.types.length,0);
            const singleProv=cat.providers.length===1;
            return(
              <div key={cat.name} style={{background:"rgba(255,255,255,0.025)",border:`1px solid ${catSel?ac(cat.name)+"55":"rgba(255,255,255,0.07)"}`,borderRadius:10,overflow:"hidden",transition:"border-color 0.3s"}}>
                <button onClick={()=>setOC(catOpen&&!isSearch?null:cat.name)} style={{width:"100%",display:"flex",alignItems:"center",gap:12,padding:"13px 16px",background:"none",border:"none",cursor:"pointer",fontFamily:"inherit"}}>
                  <span style={{fontSize:18}}>{cat.icon}</span>
                  <span style={{fontSize:14,fontWeight:600,color:ac(cat.name),flex:1,textAlign:"left"}}>{cat.name}</span>
                  <span style={{fontSize:11,color:"#4a5568",fontFamily:"var(--m)"}}>{totalTypes} types</span>
                  {catSel&&<span style={{width:8,height:8,borderRadius:4,background:ac(cat.name),flexShrink:0}}/>}
                  <span style={{color:"#6b7c93",fontSize:13,transform:catOpen?"rotate(180deg)":"none",transition:"transform 0.2s"}}>▾</span>
                </button>

                {catOpen&&(<div style={{padding:"0 8px 8px"}}>{cat.providers.map(prov=>{
                  const pk=prov.namespace,provOpen=singleProv||openProv[pk]||isSearch,provSel=hasProvSel(prov);
                  return(<div key={pk} style={{marginBottom:2}}>
                    {!singleProv&&(<button onClick={()=>setOP(s=>({...s,[pk]:!s[pk]}))} style={{width:"100%",display:"flex",alignItems:"center",gap:8,padding:"8px 10px",background:provOpen?"rgba(255,255,255,0.02)":"transparent",border:"none",borderRadius:8,cursor:"pointer",fontFamily:"inherit"}}>
                      <span style={{fontSize:11,color:ac(cat.name),opacity:0.6,transform:provOpen?"rotate(90deg)":"none",transition:"transform 0.15s"}}>▸</span>
                      <span style={{fontSize:13,fontWeight:600,color:provSel?ac(cat.name):"#8899aa",flex:1,textAlign:"left"}}>{pn(prov.namespace)}</span>
                      {provSel&&<span style={{width:6,height:6,borderRadius:3,background:ac(cat.name)}}/>}
                      <span style={{fontSize:10,color:"#4a5568",fontFamily:"var(--m)"}}>{prov.types.length}</span>
                    </button>)}
                    {provOpen&&(()=>{
                      const common=prov.types.filter(t=>(t.priority||999)<999);
                      const other=prov.types.filter(t=>(t.priority||999)>=999);
                      const renderRT=(rt)=>{
                        const rk=`${prov.namespace}|${rt.key}`;
                        const hasSearchOpMatch=searchHasOpMatch.has(rk);
                        // Only auto-expand if search matched via operation paths
                        const searchAutoExpand=isSearch&&hasSearchOpMatch;
                        const rtOpen=openRT===rk||searchAutoExpand;
                        const rtSel=hasRTSel(prov,rt);
                        const sc=rtSelCount(rt);
                        const totalOps=rt.actions.reduce((s,a)=>s+a.ops.length,0);
                        const levels=groupByLevel(rt,prov.namespace);
                        const displayName=rt.name||fn(rt.key);
                        // For manually opened: use local action filter. For search-expanded: filter ops silently.
                        const localAF=openRT===rk?actionFilter:"";
                        // Hidden search filter: filters ops but doesn't show in the input field
                        const hiddenSearchFilter=searchAutoExpand&&openRT!==rk?globalActionFilter:"";
                        // Combined filter for ActionGroup
                        const combinedFilter=localAF||hiddenSearchFilter;
                        const hlOps=searchAutoExpand?filter:"";
                        return(<div key={rt.key}>
                          <button onClick={()=>{setORT(openRT===rk?null:rk);setAF("")}} style={{width:"100%",display:"flex",alignItems:"center",gap:8,padding:"8px 10px",background:rtOpen?"rgba(255,255,255,0.04)":"transparent",border:"none",borderRadius:6,cursor:"pointer",fontFamily:"inherit",transition:"background 0.15s"}}>
                            <span style={{fontSize:11,color:"#6b7c93",transform:rtOpen?"rotate(90deg)":"none",transition:"transform 0.15s",flexShrink:0}}>▸</span>
                            <span style={{fontSize:13,fontWeight:rtSel?600:500,color:rtSel?ac(cat.name):"#b0bec5",flex:1,textAlign:"left"}}>{isSearch?<HL text={displayName} query={filter}/>:displayName}</span>
                            {sc>0&&<span style={{fontSize:11,color:ac(cat.name),fontWeight:600}}>{sc} sel.</span>}
                            <span style={{fontSize:10,color:"#4a5568",fontFamily:"var(--m)"}}>{totalOps}</span>
                          </button>

                          {/* AWS-style action panel */}
                          {rtOpen&&(<div style={{margin:"4px 0 8px",marginLeft:singleProv?8:20,padding:16,background:"rgba(255,255,255,0.02)",border:"1px solid rgba(255,255,255,0.06)",borderRadius:8}}>
                            <div style={{fontSize:12,color:"#6b7c93",marginBottom:8}}>Specify actions from <b style={{color:"#e8ecf1"}}>{displayName}</b></div>
                            {/* Action filter — always empty unless user types in it */}
                            <div style={{position:"relative",marginBottom:12}}>
                              <input value={openRT===rk?actionFilter:""} onChange={e=>{setORT(rk);setAF(e.target.value)}} onFocus={()=>{if(openRT!==rk){setORT(rk);setAF("")}}} placeholder="Filter actions..." style={{width:"100%",boxSizing:"border-box",padding:"8px 12px 8px 32px",background:"rgba(255,255,255,0.05)",border:"1px solid rgba(255,255,255,0.1)",borderRadius:6,color:"#e8ecf1",fontSize:12,fontFamily:"inherit",outline:"none"}}/>
                              <span style={{position:"absolute",left:10,top:"50%",transform:"translateY(-50%)",fontSize:14,opacity:0.3}}>⌕</span>
                            </div>
                            {levels.map(([level,ops])=>
                              <ActionGroup key={level} label={level} ops={ops} ns={prov.namespace} sel={sel} onToggle={toggleOps} actionFilter={combinedFilter.toLowerCase()} color={LVLC[level]||"#8899aa"} highlightQuery={hlOps}/>
                            )}
                          </div>)}
                        </div>);
                      };
                      return<div style={{paddingLeft:singleProv?8:20,display:"flex",flexDirection:"column",gap:1}}>
                        {common.length>0&&other.length>0&&<div style={{fontSize:10,fontWeight:600,color:"#6b7c93",textTransform:"uppercase",letterSpacing:"0.08em",padding:"8px 10px 4px",opacity:0.7}}>Commonly used</div>}
                        {common.map(renderRT)}
                        {other.length>0&&common.length>0&&<div style={{fontSize:10,fontWeight:600,color:"#4a5568",textTransform:"uppercase",letterSpacing:"0.08em",padding:"10px 10px 4px",marginTop:4,borderTop:"1px solid rgba(255,255,255,0.04)"}}>Other resources</div>}
                        {other.map(renderRT)}
                      </div>})()}
                  </div>);
                })}</div>)}
              </div>
            );
          })}
        </div>
      </div>

      {/* Results */}
      {sOps.length>0&&(
        <div ref={rRef} style={{maxWidth:960,margin:"0 auto",padding:"0 24px 60px"}}>
          <div style={{height:1,background:"rgba(255,255,255,0.06)",margin:"0 0 24px"}}/>
          <div style={{marginBottom:28}}><h3 style={HS}>Required Permissions ({sOps.length})</h3><div style={{display:"flex",flexDirection:"column",gap:3}}>{sOps.map((o,i)=><OB key={i} op={o} onRemove={removeOp}/>)}</div></div>
          <div style={{marginBottom:28}}><h3 style={HS}>Built-in Roles ({mRoles.length}){rolesStale&&<span style={{fontWeight:400,fontSize:11,color:"#6b7c93",marginLeft:8,fontStyle:"italic"}}>updating…</span>}</h3>{!mRoles.length?<div style={{padding:20,background:"rgba(233,69,96,0.08)",borderRadius:10,border:"1px solid rgba(233,69,96,0.2)",fontSize:13,color:"#e94560"}}>No built-in role covers 60%+ of required permissions.</div>:<div style={{display:"flex",flexDirection:"column",gap:10}}>{mRoles.map((r,i)=><RoleCard key={i} role={r} total={sOps.length} open={openRole===i} toggle={()=>setOR(openRole===i?null:i)}/>)}</div>}</div>
          <div style={{background:"rgba(79,195,247,0.06)",border:"1px solid rgba(79,195,247,0.15)",borderRadius:10,padding:16,marginBottom:16}}><div style={{fontSize:13,color:"#8899aa",lineHeight:1.6}}><b style={{color:"#4fc3f7"}}>ℹ Note:</b> Review whether the additional permissions in the built-in role are acceptable for your environment.</div></div>
          <div style={{marginBottom:24}}><button onClick={()=>setSJ(!showJSON)} style={{display:"inline-flex",alignItems:"center",gap:8,padding:"12px 24px",borderRadius:8,cursor:"pointer",fontFamily:"inherit",background:showJSON?"rgba(171,71,188,0.2)":"rgba(171,71,188,0.1)",border:`1px solid rgba(171,71,188,0.5)`,color:"#ce93d8",fontSize:14,fontWeight:600,boxShadow:"0 4px 14px rgba(171,71,188,0.15)",transition:"all 0.2s"}}>{showJSON?"▾":"▸"} View Custom Role JSON</button>{showJSON&&<div style={{marginTop:12,position:"relative"}}><pre style={{background:"rgba(0,0,0,0.3)",border:"1px solid rgba(255,255,255,0.08)",borderRadius:10,padding:16,overflowX:"auto",fontSize:12,lineHeight:1.6,color:"#a8c0d8",fontFamily:"var(--m)"}}>{cJSON}</pre><button onClick={()=>copy(cJSON)} style={{position:"absolute",top:10,right:10,padding:"6px 14px",borderRadius:6,cursor:"pointer",background:copied?"rgba(15,155,88,0.2)":"rgba(255,255,255,0.08)",border:`1px solid ${copied?"rgba(15,155,88,0.4)":"rgba(255,255,255,0.15)"}`,color:copied?"#0f9b58":"#8899aa",fontSize:12,fontFamily:"inherit"}}>{copied?"✓ Copied":"Copy"}</button><div style={{marginTop:8,fontSize:11,color:"#4a5568"}}>Deploy: <code style={{color:"#6b7c93"}}>New-AzRoleDefinition -InputFile custom-role.json</code></div></div>}</div>
          <div style={{background:"rgba(255,255,255,0.02)",border:"1px solid rgba(255,255,255,0.06)",borderRadius:10,padding:16,marginBottom:24}}><div style={{fontSize:12,color:"#4a5568",lineHeight:1.6}}>These are general recommendations based on Azure API data. For individual RBAC architecture reviews, security assessments, or custom least-privilege implementations — <a href="mailto:info@simonvedder.com" style={{color:"#6b7c93"}}>info@simonvedder.com</a> · <a href="https://simonvedder.com" style={{color:"#6b7c93"}}>simonvedder.com</a></div></div>
        </div>
      )}
      {!sOps.length&&<div style={{textAlign:"center",padding:"30px 24px 60px",maxWidth:960,margin:"0 auto"}}><div style={{fontSize:13,color:"#3a4556"}}>Select resources and actions above to see required permissions and matching built-in roles.</div></div>}
      <footer style={{padding:"24px",maxWidth:960,margin:"0 auto",borderTop:"1px solid rgba(255,255,255,0.05)",textAlign:"center"}}><div style={{fontSize:12,color:"#4a5568",marginBottom:8}}>Least Privilege Studio for Azure · Open Source · <a href="https://github.com/simon-vedder/least-privilege-studio" style={{color:"#4fc3f7",textDecoration:"none"}}>GitHub</a></div><div style={{fontSize:12,color:"#4a5568",marginBottom:8}}>Built by <a href="https://simonvedder.com" style={{color:"#4fc3f7",textDecoration:"none"}}>Simon Vedder</a> · <a href="https://www.linkedin.com/in/simonvedder/" style={{color:"#4fc3f7",textDecoration:"none"}}>LinkedIn</a></div><div style={{fontSize:11,color:"#3a4556",marginBottom:8}}>Always verify permissions in a non-production environment before deploying.</div><div style={{fontSize:11,color:"#3a4556"}}>No personal data collected. No cookies. <a href="https://simonvedder.com/privacy" style={{color:"#4a5568",textDecoration:"underline"}}>Privacy Policy</a> · <a href="https://simonvedder.com/terms" style={{color:"#4a5568",textDecoration:"underline"}}>Terms</a></div></footer>
    </div>
  );
}

const ROOT={"--m":"'IBM Plex Mono',monospace",minHeight:"100vh",background:"linear-gradient(170deg,#0a0a1a 0%,#111128 40%,#0d1117 100%)",color:"#c8d6e5",fontFamily:"'Instrument Sans',-apple-system,sans-serif"};
const HS={fontSize:14,fontWeight:600,color:"#8899aa",textTransform:"uppercase",letterSpacing:"0.06em",marginBottom:12};

// ─── DEMO DATA ──────────────────────────────────────────────────────────────
const DH=[{trigger:{provider:"Microsoft.Compute",resourceType:"virtualMachines",actionGroup:"Write"},hints:[{provider:"Microsoft.Compute",resourceType:"disks",actionGroup:"Write",reason:"VMs require managed disks"},{provider:"Microsoft.Network",resourceType:"networkInterfaces",actionGroup:"Write",reason:"VMs require a NIC"},{provider:"Microsoft.Network",resourceType:"networkInterfaces",actionGroup:"Action",reason:"NIC must be joined to VM"},{provider:"Microsoft.Network",resourceType:"virtualNetworks",actionGroup:"Action",reason:"NIC must join a subnet"},{provider:"Microsoft.Network",resourceType:"virtualNetworks",actionGroup:"Read",reason:"Subnet must be readable"},{provider:"Microsoft.Resources",resourceType:"subscriptions/resourceGroups",actionGroup:"Read",reason:"Resource group must be readable"}]},{trigger:{provider:"Microsoft.Network",resourceType:"networkInterfaces",actionGroup:"Write"},hints:[{provider:"Microsoft.Network",resourceType:"virtualNetworks",actionGroup:"Action",reason:"NIC must join a subnet"}]},{trigger:{provider:"Microsoft.Network",resourceType:"publicIPAddresses",actionGroup:"Write"},hints:[{provider:"Microsoft.Network",resourceType:"publicIPAddresses",actionGroup:"Action",reason:"Public IP must be joined to NIC"}]},{trigger:{provider:"Microsoft.Web",resourceType:"sites",actionGroup:"Write"},hints:[{provider:"Microsoft.Web",resourceType:"serverfarms",actionGroup:"Read",reason:"App needs an App Service Plan"},{provider:"Microsoft.Resources",resourceType:"subscriptions/resourceGroups",actionGroup:"Read",reason:"Resource group must be readable"}]}];
const DR=[{name:"Virtual Machine Contributor",id:"9980e02c",description:"Create and manage VMs. No VNet or storage access.",actions:["Microsoft.Authorization/*/read","Microsoft.Compute/availabilitySets/*","Microsoft.Compute/locations/*","Microsoft.Compute/virtualMachines/*","Microsoft.Compute/virtualMachineScaleSets/*","Microsoft.Compute/disks/write","Microsoft.Compute/disks/read","Microsoft.Compute/disks/delete","Microsoft.Insights/alertRules/*","Microsoft.Network/applicationGateways/backendAddressPools/join/action","Microsoft.Network/loadBalancers/backendAddressPools/join/action","Microsoft.Network/loadBalancers/inboundNatPools/join/action","Microsoft.Network/loadBalancers/inboundNatRules/join/action","Microsoft.Network/loadBalancers/probes/join/action","Microsoft.Network/loadBalancers/read","Microsoft.Network/locations/*","Microsoft.Network/networkInterfaces/*","Microsoft.Network/networkSecurityGroups/join/action","Microsoft.Network/networkSecurityGroups/read","Microsoft.Network/publicIPAddresses/join/action","Microsoft.Network/publicIPAddresses/read","Microsoft.Network/virtualNetworks/read","Microsoft.Network/virtualNetworks/subnets/join/action","Microsoft.ResourceHealth/availabilityStatuses/read","Microsoft.Resources/deployments/*","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Storage/storageAccounts/listKeys/action","Microsoft.Storage/storageAccounts/read","Microsoft.Support/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:59},{name:"Contributor",id:"b24988ac",description:"Full access to manage resources. Cannot assign roles.",actions:["*"],notActions:["Microsoft.Authorization/*/Delete","Microsoft.Authorization/*/Write","Microsoft.Authorization/elevateAccess/Action"],dataActions:[],notDataActions:[],_estimatedActions:5000},{name:"Reader",id:"acdd72a7",description:"View all resources.",actions:["*/read"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:3000},{name:"Network Contributor",id:"4d97b98b",description:"Create and manage networks.",actions:["Microsoft.Authorization/*/read","Microsoft.Insights/alertRules/*","Microsoft.Network/*","Microsoft.ResourceHealth/availabilityStatuses/read","Microsoft.Resources/deployments/*","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Support/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:55},{name:"Storage Account Contributor",id:"17d1049b",description:"Manage storage accounts. No data access.",actions:["Microsoft.Authorization/*/read","Microsoft.Insights/alertRules/*","Microsoft.Insights/diagnosticSettings/*","Microsoft.Network/virtualNetworks/subnets/joinViaServiceEndpoint/action","Microsoft.ResourceHealth/availabilityStatuses/read","Microsoft.Resources/deployments/*","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Storage/storageAccounts/*","Microsoft.Support/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:48},{name:"Storage Blob Data Reader",id:"2a2b9908",description:"Read blob containers and data.",actions:["Microsoft.Storage/storageAccounts/blobServices/containers/read","Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action"],notActions:[],dataActions:["Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read"],notDataActions:[],_estimatedActions:3},{name:"Storage Blob Data Contributor",id:"ba92f5b4",description:"Read, write, delete blob data.",actions:["Microsoft.Storage/storageAccounts/blobServices/containers/read","Microsoft.Storage/storageAccounts/blobServices/containers/write","Microsoft.Storage/storageAccounts/blobServices/containers/delete","Microsoft.Storage/storageAccounts/blobServices/generateUserDelegationKey/action"],notActions:[],dataActions:["Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read","Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write","Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete"],notDataActions:[],_estimatedActions:9},{name:"Key Vault Contributor",id:"f25e0fa2",description:"Manage key vaults. No data access.",actions:["Microsoft.Authorization/*/read","Microsoft.Insights/alertRules/*","Microsoft.KeyVault/*","Microsoft.Resources/deployments/*","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Support/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:48},{name:"Website Contributor",id:"de139f84",description:"Manage websites.",actions:["Microsoft.Authorization/*/read","Microsoft.Insights/alertRules/*","Microsoft.Insights/components/*","Microsoft.ResourceHealth/availabilityStatuses/read","Microsoft.Resources/deployments/*","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Support/*","Microsoft.Web/certificates/*","Microsoft.Web/listSitesAssignedToHostName/read","Microsoft.Web/serverFarms/join/action","Microsoft.Web/serverFarms/read","Microsoft.Web/sites/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:42},{name:"SQL DB Contributor",id:"9b7fa17d",description:"Manage SQL databases.",actions:["Microsoft.Authorization/*/read","Microsoft.Insights/alertRules/*","Microsoft.ResourceHealth/availabilityStatuses/read","Microsoft.Resources/deployments/*","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Sql/locations/*/read","Microsoft.Sql/servers/databases/*","Microsoft.Sql/servers/read","Microsoft.Support/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:42},{name:"User Access Administrator",id:"18d7d88d",description:"Manage user access.",actions:["*/read","Microsoft.Authorization/*","Microsoft.Support/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:3040},{name:"Desktop Virtualization Contributor",id:"082f0a83",description:"Desktop Virtualization contributor.",actions:["Microsoft.DesktopVirtualization/*","Microsoft.Resources/subscriptions/resourceGroups/read","Microsoft.Resources/deployments/*","Microsoft.Authorization/*/read","Microsoft.Insights/alertRules/*","Microsoft.Support/*"],notActions:[],dataActions:[],notDataActions:[],_estimatedActions:48}];
const _t=(p,k,a)=>({key:k,name:k,provider:p,totalOps:a.reduce((s,x)=>s+x.ops.length,0),actions:a});const _a=(l,o,h=false)=>({label:l,ops:o,hasDataActions:h});const _o=(a,t="action")=>({action:a,type:t});
const DC=[
  {name:"Compute",icon:"🖥",providers:[{namespace:"Microsoft.Compute",displayName:"Compute",types:[
    _t("Microsoft.Compute","virtualMachines",[
      _a("Read",[_o("Microsoft.Compute/virtualMachines/read"),_o("Microsoft.Compute/virtualMachines/instanceView/read"),_o("Microsoft.Compute/virtualMachines/extensions/read")]),
      _a("Write",[_o("Microsoft.Compute/virtualMachines/write"),_o("Microsoft.Compute/virtualMachines/extensions/write")]),
      _a("Delete",[_o("Microsoft.Compute/virtualMachines/delete"),_o("Microsoft.Compute/virtualMachines/extensions/delete")]),
      _a("Action",[_o("Microsoft.Compute/virtualMachines/start/action"),_o("Microsoft.Compute/virtualMachines/deallocate/action"),_o("Microsoft.Compute/virtualMachines/powerOff/action"),_o("Microsoft.Compute/virtualMachines/restart/action"),_o("Microsoft.Compute/virtualMachines/runCommand/action")]),
    ]),
    _t("Microsoft.Compute","disks",[_a("Read",[_o("Microsoft.Compute/disks/read")]),_a("Write",[_o("Microsoft.Compute/disks/write")]),_a("Delete",[_o("Microsoft.Compute/disks/delete")])]),
    _t("Microsoft.Compute","galleries",[_a("Read",[_o("Microsoft.Compute/galleries/read"),_o("Microsoft.Compute/galleries/images/read"),_o("Microsoft.Compute/galleries/images/versions/read")]),_a("Write",[_o("Microsoft.Compute/galleries/write"),_o("Microsoft.Compute/galleries/images/write"),_o("Microsoft.Compute/galleries/images/versions/write")])]),
  ]}]},
  {name:"Networking",icon:"🌐",providers:[{namespace:"Microsoft.Network",displayName:"Network",types:[
    _t("Microsoft.Network","virtualNetworks",[
      _a("Read",[_o("Microsoft.Network/virtualNetworks/read"),_o("Microsoft.Network/virtualNetworks/subnets/read")]),
      _a("Write",[_o("Microsoft.Network/virtualNetworks/write"),_o("Microsoft.Network/virtualNetworks/subnets/write")]),
      _a("Delete",[_o("Microsoft.Network/virtualNetworks/delete"),_o("Microsoft.Network/virtualNetworks/subnets/delete")]),
      _a("Action",[_o("Microsoft.Network/virtualNetworks/subnets/join/action")]),
    ]),
    _t("Microsoft.Network","networkInterfaces",[_a("Read",[_o("Microsoft.Network/networkInterfaces/read")]),_a("Write",[_o("Microsoft.Network/networkInterfaces/write")]),_a("Delete",[_o("Microsoft.Network/networkInterfaces/delete")]),_a("Action",[_o("Microsoft.Network/networkInterfaces/join/action")])]),
    _t("Microsoft.Network","publicIPAddresses",[_a("Read",[_o("Microsoft.Network/publicIPAddresses/read")]),_a("Write",[_o("Microsoft.Network/publicIPAddresses/write")]),_a("Delete",[_o("Microsoft.Network/publicIPAddresses/delete")]),_a("Action",[_o("Microsoft.Network/publicIPAddresses/join/action")])]),
    _t("Microsoft.Network","networkSecurityGroups",[_a("Read",[_o("Microsoft.Network/networkSecurityGroups/read"),_o("Microsoft.Network/networkSecurityGroups/securityRules/read")]),_a("Write",[_o("Microsoft.Network/networkSecurityGroups/write"),_o("Microsoft.Network/networkSecurityGroups/securityRules/write")]),_a("Delete",[_o("Microsoft.Network/networkSecurityGroups/delete")]),_a("Action",[_o("Microsoft.Network/networkSecurityGroups/join/action")])]),
    _t("Microsoft.Network","loadBalancers",[_a("Read",[_o("Microsoft.Network/loadBalancers/read")]),_a("Write",[_o("Microsoft.Network/loadBalancers/write")]),_a("Delete",[_o("Microsoft.Network/loadBalancers/delete")])]),
    _t("Microsoft.Network","dnsZones",[_a("Read",[_o("Microsoft.Network/dnsZones/read"),_o("Microsoft.Network/dnsZones/A/read"),_o("Microsoft.Network/dnsZones/AAAA/read"),_o("Microsoft.Network/dnsZones/CNAME/read"),_o("Microsoft.Network/dnsZones/NS/read")]),_a("Write",[_o("Microsoft.Network/dnsZones/write"),_o("Microsoft.Network/dnsZones/A/write"),_o("Microsoft.Network/dnsZones/AAAA/write"),_o("Microsoft.Network/dnsZones/CNAME/write")]),_a("Delete",[_o("Microsoft.Network/dnsZones/delete")])]),
  ]}]},
  {name:"Storage",icon:"📦",providers:[{namespace:"Microsoft.Storage",displayName:"Storage",types:[
    _t("Microsoft.Storage","storageAccounts",[
      _a("Read",[_o("Microsoft.Storage/storageAccounts/read"),_o("Microsoft.Storage/storageAccounts/blobServices/containers/read"),_o("Microsoft.Storage/storageAccounts/fileServices/fileshares/read"),_o("Microsoft.Storage/storageAccounts/tableServices/tables/read"),_o("Microsoft.Storage/storageAccounts/queueServices/queues/read")]),
      _a("Write",[_o("Microsoft.Storage/storageAccounts/write"),_o("Microsoft.Storage/storageAccounts/blobServices/containers/write"),_o("Microsoft.Storage/storageAccounts/fileServices/fileshares/write"),_o("Microsoft.Storage/storageAccounts/tableServices/tables/write")]),
      _a("Delete",[_o("Microsoft.Storage/storageAccounts/delete"),_o("Microsoft.Storage/storageAccounts/blobServices/containers/delete"),_o("Microsoft.Storage/storageAccounts/fileServices/fileshares/delete")]),
      _a("Action",[_o("Microsoft.Storage/storageAccounts/listKeys/action"),_o("Microsoft.Storage/storageAccounts/blobServices/containers/blobs/read","dataAction"),_o("Microsoft.Storage/storageAccounts/blobServices/containers/blobs/write","dataAction"),_o("Microsoft.Storage/storageAccounts/blobServices/containers/blobs/delete","dataAction")],true),
    ]),
  ]}]},
  {name:"Databases",icon:"🗄",providers:[{namespace:"Microsoft.Sql",displayName:"SQL",types:[
    _t("Microsoft.Sql","servers",[_a("Read",[_o("Microsoft.Sql/servers/read"),_o("Microsoft.Sql/servers/databases/read")]),_a("Write",[_o("Microsoft.Sql/servers/write"),_o("Microsoft.Sql/servers/databases/write")]),_a("Delete",[_o("Microsoft.Sql/servers/delete"),_o("Microsoft.Sql/servers/databases/delete")])]),
  ]},{namespace:"Microsoft.DocumentDB",displayName:"Cosmos DB",types:[
    _t("Microsoft.DocumentDB","databaseAccounts",[_a("Read",[_o("Microsoft.DocumentDB/databaseAccounts/read")]),_a("Write",[_o("Microsoft.DocumentDB/databaseAccounts/write")]),_a("Delete",[_o("Microsoft.DocumentDB/databaseAccounts/delete")])]),
  ]}]},
  {name:"Web + Serverless",icon:"🌍",providers:[{namespace:"Microsoft.Web",displayName:"App Service",types:[
    _t("Microsoft.Web","sites",[_a("Read",[_o("Microsoft.Web/sites/read")]),_a("Write",[_o("Microsoft.Web/sites/write")]),_a("Delete",[_o("Microsoft.Web/sites/delete")])]),
    _t("Microsoft.Web","serverfarms",[_a("Read",[_o("Microsoft.Web/serverfarms/read")]),_a("Write",[_o("Microsoft.Web/serverfarms/write")]),_a("Delete",[_o("Microsoft.Web/serverfarms/delete")])]),
  ]}]},
  {name:"Security",icon:"🔐",providers:[{namespace:"Microsoft.KeyVault",displayName:"Key Vault",types:[
    _t("Microsoft.KeyVault","vaults",[_a("Read",[_o("Microsoft.KeyVault/vaults/read"),_o("Microsoft.KeyVault/vaults/secrets/read"),_o("Microsoft.KeyVault/vaults/keys/read")]),_a("Write",[_o("Microsoft.KeyVault/vaults/write"),_o("Microsoft.KeyVault/vaults/secrets/write"),_o("Microsoft.KeyVault/vaults/keys/write"),_o("Microsoft.KeyVault/vaults/accessPolicies/write")]),_a("Delete",[_o("Microsoft.KeyVault/vaults/delete"),_o("Microsoft.KeyVault/vaults/secrets/delete")])]),
  ]}]},
  {name:"Management + Governance",icon:"⚙",providers:[{namespace:"Microsoft.Resources",displayName:"Resource Manager",types:[
    _t("Microsoft.Resources","subscriptions/resourceGroups",[_a("Read",[_o("Microsoft.Resources/subscriptions/resourceGroups/read")]),_a("Write",[_o("Microsoft.Resources/subscriptions/resourceGroups/write")]),_a("Delete",[_o("Microsoft.Resources/subscriptions/resourceGroups/delete")])]),
    _t("Microsoft.Resources","deployments",[_a("Read",[_o("Microsoft.Resources/deployments/read")]),_a("Write",[_o("Microsoft.Resources/deployments/write")]),_a("Delete",[_o("Microsoft.Resources/deployments/delete")])]),
  ]},{namespace:"Microsoft.Authorization",displayName:"Authorization",types:[
    _t("Microsoft.Authorization","roleAssignments",[_a("Read",[_o("Microsoft.Authorization/roleAssignments/read"),_o("Microsoft.Authorization/roleDefinitions/read")]),_a("Write",[_o("Microsoft.Authorization/roleAssignments/write")]),_a("Delete",[_o("Microsoft.Authorization/roleAssignments/delete")])]),
  ]}]},
  {name:"Desktop Virtualization",icon:"🖵",providers:[{namespace:"Microsoft.DesktopVirtualization",displayName:"Virtual Desktop",types:[
    _t("Microsoft.DesktopVirtualization","hostpools",[_a("Read",[_o("Microsoft.DesktopVirtualization/hostpools/read"),_o("Microsoft.DesktopVirtualization/hostpools/sessionhosts/read")]),_a("Write",[_o("Microsoft.DesktopVirtualization/hostpools/write"),_o("Microsoft.DesktopVirtualization/hostpools/sessionhosts/write")]),_a("Delete",[_o("Microsoft.DesktopVirtualization/hostpools/delete"),_o("Microsoft.DesktopVirtualization/hostpools/sessionhosts/delete")])]),
  ]}]},
];
